#!/usr/bin/env python3
"""Build the NPC Friends x Heap of Foods patch package.

Merges the Lua modules that also power the standalone mod into a single drop-in
file for NPC Friends, then assembles the ready-to-run zip:

    NPC_HOF_Patch/
        install.bat            <- double-click this
        restore.bat            <- undo
        diagnose.bat           <- dump the current state to 진단결과.txt
        README.txt
        files/npc_hof_cooking.lua
        tools/patch.ps1

The package deliberately ships none of NPC Friends' own code. install.bat backs
up the one file it edits and appends a single line to it, so there is nothing of
theirs to redistribute.
"""

from __future__ import annotations

import re
import shutil
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PATCH = REPO / "patch"
SCRIPTS = REPO / "npcfriends_hof_cooking" / "scripts"
BUILD = REPO / "build" / "NPC_HOF_Patch"
DIST = REPO / "dist"

PACKAGE_NAME = "NPC_HOF_Patch"

# Order matters: later modules use the locals declared by earlier ones.
MERGE_ORDER = [
    (SCRIPTS / "hofnpc_core.lua", "Core"),
    (SCRIPTS / "hofnpc_variety.lua", "Variety"),
    (SCRIPTS / "hofnpc_search.lua", "Search"),
    (SCRIPTS / "hofnpc_diag.lua", "Diag"),
]

# `local Core = require("hofnpc_core")` and friends: inside the merged file the
# locals are already in scope, so these lines must go.
CROSS_REQUIRE = re.compile(r'^\s*local\s+\w+\s*=\s*require\(\s*"hofnpc_[a-z]+"\s*\)\s*$')


def strip_module(path: Path, returns: str) -> str:
    """Drop the cross-module requires and the trailing `return X`."""
    lines = path.read_text(encoding="utf-8").splitlines()

    kept = [line for line in lines if not CROSS_REQUIRE.match(line)]

    trailing = re.compile(rf"^\s*return\s+{re.escape(returns)}\s*$")
    for index in range(len(kept) - 1, -1, -1):
        if trailing.match(kept[index]):
            del kept[index]
            break
    else:
        raise SystemExit(f"{path.name}: could not find `return {returns}`")

    return "\n".join(kept).rstrip() + "\n"


def build_lua() -> str:
    banner = (
        "-- " + "=" * 74 + "\n"
        f"--  {'':<2}이 파일은 patch/build.py 가 자동으로 만든 파일입니다.\n"
        "--  Generated by patch/build.py -- edit the sources under\n"
        "--  npcfriends_hof_cooking/scripts/ instead of editing this file.\n"
        "-- " + "=" * 74 + "\n\n"
    )

    parts = [banner, (PATCH / "header.lua").read_text(encoding="utf-8")]

    for path, returns in MERGE_ORDER:
        parts.append("\n\n" + "-" * 78 + f"\n-- {path.name}\n" + "-" * 78 + "\n\n")
        parts.append(strip_module(path, returns))

    parts.append("\n\n")
    parts.append((PATCH / "install_stub.lua").read_text(encoding="utf-8"))

    return "".join(parts)


README = """\
====================================================================
  NPC Friends x Heap of Foods - 요리 연동 패치
====================================================================

NPC Friends 의 왈리 NPC 가 Heap of Foods 를 비롯한 음식 모드의 요리를
전부 인식하고, 여러 가지 요리를 돌아가며 만들도록 고쳐 줍니다.


[ 무엇이 문제였나 ]

  NPC Friends 는 "왈리가 만들 수 있는 요리" 목록을 모드 안에 손으로
  적어 두었습니다 (scripts/npc/npc_cooking_recipes.lua).
  거기에는 바닐라 요리와 일부 모드 요리만 들어 있어서, Heap of Foods 가
  추가한 200종이 넘는 요리는 창고에 재료가 아무리 많아도 후보에 오르지
  않습니다.

  게다가 요리를 고르는 함수 맨 앞에 "창고에 미트볼이 없으면 무조건
  미트볼부터" 라는 규칙이 박혀 있어서, 같은 요리만 계속 나옵니다.


[ 이 패치가 하는 일 ]

  요리 목록을 200개 더 적어 넣는 대신, 왈리가 쓸 수 있는 재료로 조합을
  만들어 보고 게임 자체의 요리 판정 함수(cooking.CalculateRecipe)에
  "이 조합은 무슨 요리가 되나?" 하고 직접 물어봅니다.

  그래서 정상적인 방법으로 등록된 음식 모드라면 무엇이든 자동으로
  인식됩니다. Heap of Foods 가 업데이트로 요리를 더 추가해도 이 패치는
  그대로 두면 됩니다.

  여기에 "최근에 만든 요리"와 "이미 창고에 쌓인 요리"에 감점을 주어
  메뉴가 계속 바뀌도록 했습니다.


[ 설치 ]

  1. 이 zip 을 폴더째 압축 해제합니다. (압축 안에서 바로 실행하면 안 됩니다)
  2. DST 를 완전히 종료합니다.
  3. install.bat 을 더블클릭합니다.
  4. DST 를 다시 실행하고, Heap of Foods 와 NPC Friends 를 둘 다 켠 채로
     월드에 들어갑니다.
  5. 왈리 NPC 에게 냄비와 아이스박스를 지정하고 요리를 시켜 봅니다.

  권한 오류가 나면 install.bat 을 마우스 오른쪽 클릭 ->
  "관리자 권한으로 실행" 을 해 주세요.


[ 되돌리기 ]

  restore.bat 을 더블클릭하면 원래대로 돌아갑니다.
  원본은 설치할 때 _backup 폴더에 보관됩니다.


[ 설정 바꾸기 ]

  files\\npc_hof_cooking.lua 를 메모장으로 열면 맨 위에 USER_SETTINGS 가
  있습니다. 값을 고친 뒤 install.bat 을 다시 실행하면 적용됩니다.

    variety        요리 다양성   "off" / "low" / "medium" / "high"
    budget         탐색량        "low" / "medium" / "high"
    same_dish_max  같은 요리를 창고에 몇 개까지 쌓을지 (0 = 모드 설정 따름)
    allow_negative 체력/정신력이 깎이는 요리도 만들지
    explain        요리를 못 할 때 왈리가 그 이유를 직접 말함 (기본 켜짐)
    debug          고른 이유까지 전부 서버 로그에 출력


[ 왈리가 "재료가 없어요" 라고 할 때 ]

  왈리는 창고 전체를 보지 않습니다. '여기서 요리' 로 지정한 지점 기준
  반경 약 17칸 안에 있는, 아이스박스/상자류만 봅니다.

  이 패치를 깔면 왈리가 왜 못 하는지 직접 말해 줍니다. 예를 들어

    "상자 3개를 봤는데 요리 재료가 없어요. 제 상자에 넣어 주세요."
    "요리 지점 근처에 냄비가 없어요."
    "가방이 꽉 차서 재료를 못 들어요."
    "재료는 12종 있는데 만들 수 있는 요리가 없어요."

  가장 흔한 원인은 첫 번째입니다. 왈리는 자기가 지은 아이스박스 1개와
  나무상자 2개를 씁니다. 재료를 그 3개 안에 넣어 주시거나,
  재료 상자 옆에서 '여기서 요리' 를 다시 지정해 주세요.

  마지막 줄이 나오면 '같은 요리 최대 개수' 를 올려 보세요.
  이미 만들 수 있는 요리를 전부 상한까지 쌓아 둔 상태일 수 있습니다.


[ 알아두실 점 ]

  * Steam 이 NPC Friends 를 업데이트하면 이 패치는 지워집니다.
    그때는 install.bat 을 다시 한 번 실행해 주세요.

  * 멀티에서는 서버(호스트) 쪽에 설치되어 있어야 효과가 있습니다.
    NPC 의 요리 판단은 전부 서버에서 이루어지기 때문입니다.

  * 건드리는 파일은 scripts/npc/npc_cooking_planner.lua 하나뿐이고,
    그것도 맨 끝에 아래 한 줄을 넣는 것이 전부입니다.

      pcall(function() require("npc/npc_hof_cooking").Install(CookingPlanner) end)

  * 문제가 생기면 USER_SETTINGS 의 debug 를 true 로 바꾸고 서버 로그의
    [NPCF-HOF] 줄을 확인해 주세요.
"""


def main() -> None:
    if BUILD.exists():
        shutil.rmtree(BUILD)
    (BUILD / "files").mkdir(parents=True)
    (BUILD / "tools").mkdir(parents=True)
    DIST.mkdir(exist_ok=True)

    # The merged Lua file: plain UTF-8, no BOM, LF endings -- exactly like the
    # files already inside NPC Friends.
    lua = build_lua()
    (BUILD / "files" / "npc_hof_cooking.lua").write_bytes(lua.encode("utf-8"))

    # Windows PowerShell 5.1 only decodes a .ps1 as UTF-8 when it has a BOM,
    # and this one contains Korean.
    ps1 = (PATCH / "templates" / "tools" / "patch.ps1").read_text(encoding="utf-8")
    (BUILD / "tools" / "patch.ps1").write_bytes(
        b"\xef\xbb\xbf" + ps1.replace("\n", "\r\n").encode("utf-8")
    )

    # cmd.exe wants CRLF; these two are ASCII-only on purpose.
    for name in ("install.bat", "restore.bat", "diagnose.bat"):
        text = (PATCH / "templates" / name).read_text(encoding="utf-8")
        text.encode("ascii")  # fail the build if Korean sneaks in
        (BUILD / name).write_bytes(text.replace("\n", "\r\n").encode("ascii"))

    (BUILD / "README.txt").write_bytes(
        b"\xef\xbb\xbf" + README.replace("\n", "\r\n").encode("utf-8")
    )

    archive = DIST / f"{PACKAGE_NAME}.zip"
    if archive.exists():
        archive.unlink()

    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(BUILD.rglob("*")):
            if path.is_file():
                zf.write(path, f"{PACKAGE_NAME}/{path.relative_to(BUILD).as_posix()}")

    print(f"built {archive.relative_to(REPO)}  ({archive.stat().st_size:,} bytes)")
    for path in sorted(BUILD.rglob("*")):
        if path.is_file():
            print(f"  {path.stat().st_size:>8,}  {path.relative_to(BUILD).as_posix()}")


if __name__ == "__main__":
    main()
