#!/usr/bin/env python3
"""Build the NPC Friends x Heap of Foods patch package.

Merges the Lua modules that also power the standalone mod into a single drop-in
file for NPC Friends, then assembles the ready-to-run zip:

    NPC_HOF_Patch/
        install.bat            <- double-click this
        restore.bat            <- undo
        diagnose.bat           <- dump the current state to 진단결과.txt
        collect.bat            <- pack everything needed for support into one zip
        collectmods.bat        <- pack the code of every installed mod
        lasterror.bat          <- find why the server will not start
        modcheck.bat           <- list which mods collide with which
        bisect.bat             <- halve the mod list until the culprit is found
        translate.bat          <- collect every mod's text for translating
        korean.bat             <- switch mods to the Korean they already ship
        hangul.bat             <- install the Korean string patch into the game
        README.txt
        files/npc_hof_cooking.lua
        tools/patch.ps1

The package deliberately ships none of NPC Friends' own code. install.bat backs
up the one file it edits and appends a single line to it, so there is nothing of
theirs to redistribute.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PATCH = REPO / "patch"
SCRIPTS = REPO / "npcfriends_hof_cooking" / "scripts"
BUILD = REPO / "build" / "NPC_HOF_Patch"
DIST = REPO / "dist"

PACKAGE_NAME = "NPC_HOF_Patch"

# Order matters: later modules use the locals declared by earlier ones.
MERGE_ORDER = [
    (SCRIPTS / "hofnpc_core.lua", "Core"),
    (SCRIPTS / "hofnpc_slots.lua", "Slots"),
    (SCRIPTS / "hofnpc_variety.lua", "Variety"),
    (SCRIPTS / "hofnpc_search.lua", "Search"),
    (SCRIPTS / "hofnpc_diag.lua", "Diag"),
]

# `local Core = require("hofnpc_core")` and friends: inside the merged file the
# locals are already in scope, so these lines must go.
CROSS_REQUIRE = re.compile(r'^\s*local\s+\w+\s*=\s*require\(\s*"hofnpc_[a-z]+"\s*\)\s*$')


def strip_module(path: Path, returns: str) -> str:
    """Drop the cross-module requires and the trailing `return X`."""
    lines = path.read_text(encoding="utf-8").splitlines()

    kept = [line for line in lines if not CROSS_REQUIRE.match(line)]

    trailing = re.compile(rf"^\s*return\s+{re.escape(returns)}\s*$")
    for index in range(len(kept) - 1, -1, -1):
        if trailing.match(kept[index]):
            del kept[index]
            break
    else:
        raise SystemExit(f"{path.name}: could not find `return {returns}`")

    return "\n".join(kept).rstrip() + "\n"


def build_lua() -> str:
    banner = (
        "-- " + "=" * 74 + "\n"
        f"--  {'':<2}이 파일은 patch/build.py 가 자동으로 만든 파일입니다.\n"
        "--  Generated by patch/build.py -- edit the sources under\n"
        "--  npcfriends_hof_cooking/scripts/ instead of editing this file.\n"
        "-- " + "=" * 74 + "\n\n"
    )

    parts = [banner, (PATCH / "header.lua").read_text(encoding="utf-8")]

    for path, returns in MERGE_ORDER:
        parts.append("\n\n" + "-" * 78 + f"\n-- {path.name}\n" + "-" * 78 + "\n\n")
        parts.append(strip_module(path, returns))

    parts.append("\n\n")
    parts.append((PATCH / "install_stub.lua").read_text(encoding="utf-8"))

    return "".join(parts)


README = """\
====================================================================
  NPC Friends x Heap of Foods - 요리 연동 패치
====================================================================

NPC Friends 의 왈리 NPC 가 Heap of Foods 를 비롯한 음식 모드의 요리를
전부 인식하고, 여러 가지 요리를 돌아가며 만들도록 고쳐 줍니다.


[ 무엇이 문제였나 ]

  NPC Friends 는 "왈리가 만들 수 있는 요리" 목록을 모드 안에 손으로
  적어 두었습니다 (scripts/npc/npc_cooking_recipes.lua).
  거기에는 바닐라 요리와 일부 모드 요리만 들어 있어서, Heap of Foods 가
  추가한 200종이 넘는 요리는 창고에 재료가 아무리 많아도 후보에 오르지
  않습니다.

  게다가 요리를 고르는 함수 맨 앞에 "창고에 미트볼이 없으면 무조건
  미트볼부터" 라는 규칙이 박혀 있어서, 같은 요리만 계속 나옵니다.


[ 이 패치가 하는 일 ]

  요리 목록을 200개 더 적어 넣는 대신, 왈리가 쓸 수 있는 재료로 조합을
  만들어 보고 게임 자체의 요리 판정 함수(cooking.CalculateRecipe)에
  "이 조합은 무슨 요리가 되나?" 하고 직접 물어봅니다.

  그래서 정상적인 방법으로 등록된 음식 모드라면 무엇이든 자동으로
  인식됩니다. Heap of Foods 가 업데이트로 요리를 더 추가해도 이 패치는
  그대로 두면 됩니다.

  여기에 "최근에 만든 요리"와 "이미 창고에 쌓인 요리"에 감점을 주어
  메뉴가 계속 바뀌도록 했습니다.


[ 설치 ]

  1. 이 zip 을 폴더째 압축 해제합니다. (압축 안에서 바로 실행하면 안 됩니다)
  2. DST 를 완전히 종료합니다.
  3. install.bat 을 더블클릭합니다.
  4. DST 를 다시 실행하고, Heap of Foods 와 NPC Friends 를 둘 다 켠 채로
     월드에 들어갑니다.
  5. 왈리 NPC 에게 냄비와 아이스박스를 지정하고 요리를 시켜 봅니다.

  권한 오류가 나면 install.bat 을 마우스 오른쪽 클릭 ->
  "관리자 권한으로 실행" 을 해 주세요.


[ 되돌리기 ]

  restore.bat 을 더블클릭하면 원래대로 돌아갑니다.
  원본은 설치할 때 _backup 폴더에 보관됩니다.


[ 문제가 생겼을 때 - collect.bat ]

  collect.bat 을 더블클릭하면, 문제를 보는 데 필요한 것만 알아서 골라
  zip 하나로 묶어 줍니다. 그 zip 만 보내 주시면 됩니다.

  담기는 것:
    - 지금 설치 상태 (파일별로 원본인지 / 다른 패치가 고쳤는지 판정)
    - 요리 관련 lua 파일 10개
    - DST 로그에서 요리 관련 줄만 최근 400줄
    - 켜져 있는 모드 목록 (modoverrides.lua)

  계정 이름, 스팀 ID 같은 것은 <가림> 으로 바꿔서 담습니다.

  모드 폴더를 못 찾으면, 3684000581 폴더를 collect.bat 위로
  드래그해서 놓으시면 됩니다.

  로그가 비어 있으면 files\npc_hof_cooking.lua 의 debug 를 true 로
  바꾸고 install.bat 을 다시 실행한 뒤, 게임에서 요리를 몇 번 시켜 보고
  collect.bat 을 실행해 주세요. NPC Friends 자체 요리 로그까지 같이 켜집니다.


[ 설정 바꾸기 ]

  files\\npc_hof_cooking.lua 를 메모장으로 열면 맨 위에 USER_SETTINGS 가
  있습니다. 값을 고친 뒤 install.bat 을 다시 실행하면 적용됩니다.

    variety        요리 다양성   "off" / "low" / "medium" / "high"
    budget         탐색량        "low" / "medium" / "high"
    same_dish_max  같은 요리를 창고에 몇 개까지 쌓을지 (0 = 모드 설정 따름)
    allow_negative 체력/정신력이 깎이는 요리도 만들지
    explain        요리를 못 할 때 왈리가 그 이유를 직접 말함 (기본 켜짐)
    debug          고른 이유까지 전부 서버 로그에 출력


[ 왈리가 "재료가 없어요" 라고 할 때 ]

  왈리는 창고 전체를 보지 않습니다. '여기서 요리' 로 지정한 지점 기준
  반경 약 17칸 안에 있는, 아이스박스/상자류만 봅니다.

  이 패치를 깔면 왈리가 왜 못 하는지 직접 말해 줍니다. 예를 들어

    "상자 3개를 봤는데 요리 재료가 없어요. 제 상자에 넣어 주세요."
    "요리 지점 근처에 냄비가 없어요."
    "가방이 꽉 차서 재료를 못 들어요."
    "재료는 12종 있는데 만들 수 있는 요리가 없어요."

  가장 흔한 원인은 첫 번째입니다. 왈리는 자기가 지은 아이스박스 1개와
  나무상자 2개를 씁니다. 재료를 그 3개 안에 넣어 주시거나,
  재료 상자 옆에서 '여기서 요리' 를 다시 지정해 주세요.

  마지막 줄이 나오면 '같은 요리 최대 개수' 를 올려 보세요.
  이미 만들 수 있는 요리를 전부 상한까지 쌓아 둔 상태일 수 있습니다.


[ 알아두실 점 ]

  * Steam 이 NPC Friends 를 업데이트하면 이 패치는 지워집니다.
    그때는 install.bat 을 다시 한 번 실행해 주세요.

  * 멀티에서는 서버(호스트) 쪽에 설치되어 있어야 효과가 있습니다.
    NPC 의 요리 판단은 전부 서버에서 이루어지기 때문입니다.

  * 건드리는 파일은 scripts/npc/npc_cooking_planner.lua 하나뿐이고,
    그것도 맨 끝에 아래 한 줄을 넣는 것이 전부입니다.

      pcall(function() require("npc/npc_hof_cooking").Install(CookingPlanner) end)

  * 문제가 생기면 USER_SETTINGS 의 debug 를 true 로 바꾸고 서버 로그의
    [NPCF-HOF] 줄을 확인해 주세요.


[ 문제가 생겼을 때 - collect.bat ]

  collect.bat 을 더블클릭하면, 이 패치와 관련된 것만 골라 zip 하나로
  묶어 줍니다. 설치 상태 판정, 요리 관련 lua 10개, 로그의 요리 관련 줄,
  켜져 있는 모드 목록이 들어갑니다.

  diagnose.bat 은 같은 내용을 압축 없이 진단결과.txt 로만 뽑습니다.


[ 설치된 모드를 전부 보내고 싶을 때 - collectmods.bat ]

  collectmods.bat 은 설치된 모든 DST 모드의 "코드"만 골라 담습니다.

  모드 폴더를 통째로 압축하면 보통 수 GB 입니다. 대부분이 애니메이션(.zip),
  텍스처(.tex), 사운드(.fsb/.fev) 라서 문제를 보는 데는 쓸모가 없습니다.
  실측으로 모드 2개 199 MB 가 3.8 MB 가 됩니다.

    담는 것   .lua .json .xml .txt .md .po .ini .cfg
    빼는 것   anim/ sound/ images/ bigportraits/ exported/ minimap/
              levels/textures/ levels/tiles/ 와 3 MB 넘는 파일

  모드를 하나도 못 담았더라도, 모든 모드는 모드목록.txt 에 반드시 나옵니다
  (이름 / 버전 / api / 파일 수 / 진짜 용량).

  모드를 못 찾으면 모드가 들어 있는 폴더를 collectmods.bat 위로 드래그하세요.
  보통 이 경로입니다:

    ...\\steamapps\\workshop\\content\\322330


[ 어떤 모드가 문제인지 알고 싶을 때 - modcheck.bat ]

  modcheck.bat 을 더블클릭하면, 설치된 모드의 lua 를 전부 읽어서
  모드끼리 부딪칠 수 있는 지점만 골라 모드점검.txt 로 뽑아 줍니다.

    1  서버가 안 켜지게 만들 수 있는 것
       WX-78 모듈 자리 계산. 바닐라 wx78_moduledefs.lua 안에
         assert(module_netid < 64, "To support additional WX modules, ...")
       가 있고 바닐라가 23 개를 먼저 씁니다. 모드 몫은 40 개뿐이라,
       넘기면 서버가 통째로 안 켜집니다. 어느 모드가 몇 개를 쓰는지 셉니다.
       오류 화면을 자기 코드로 바꾸는 모드도 여기서 짚습니다. 그런 모드가
       있으면 다른 모드의 사소한 오류 하나가 "서버 시작 실패" 로 커집니다.

    2  왈리 요리에 끼어들 수 있는 모드
       상자 내부, 냄비, 요리 계산식을 건드리는 모드. 그리고 같은 냄비 요리
       이름을 두 모드가 동시에 쓰는 경우 (나중에 켜진 쪽만 남습니다).

    3  로그가 직접 이름을 부른 모드
       가장 확실한 증거입니다. 최근 로그에서 MOD ERROR 로 찍혔거나
       오류 스택에 그 모드 파일이 나온 것만 추립니다.

    4  참고
       낡은 api_version, 서버에선 아무 일도 안 하는 client_only 모드,
       서버에 켜 놓았는데 설치가 안 된 모드.

  modoverrides.lua 를 찾으면 "서버에 켜져 있는 모드"만 계산에 넣습니다.
  구독만 해 놓고 꺼 둔 모드는 아무 자리도 차지하지 않기 때문입니다.

  모드를 못 찾으면 모드가 들어 있는 폴더를 modcheck.bat 위로 드래그하세요.


[ 서버가 아예 안 켜질 때 - lasterror.bat ]

  "데디케이티드 서버 시작 실패" 가 뜨면 lasterror.bat 을 더블클릭하세요.
  가장 최근 로그에서 진짜 오류 줄만 찾아 앞뒤 문맥까지 같이 뽑아
  서버오류.txt 로 저장하고, 화면에도 그대로 보여 줍니다.

  거의 항상 원인은 모드 하나입니다. 오류 줄에 나오는
  workshop-<숫자> 가 범인이고, 그 모드를 끄면 켜집니다.


[ 서버가 안 켜지는데 로그로도 모르겠을 때 - bisect.bat ]

  로그가 모드 이름을 안 찍어 주는 경우가 있습니다. 그때 씁니다.

  켜져 있는 모드를 절반씩 잘라 가며, 어느 쪽에 범인이 있는지 좁힙니다.
  모드 48 개면 48 번이 아니라 열 번 안쪽이면 끝납니다. 두 모드가 "같이
  켜져 있을 때만" 터지는 경우도 찾습니다 (그건 스무 번쯤 걸립니다).

  쓰는 법은 이것뿐입니다:

    1  bisect.bat 실행
    2  서버를 켜 본다 (켜지든 안 켜지든 상관없음)
    3  bisect.bat 다시 실행
    4  범인 이름이 나올 때까지 2~3 반복

  bisect.bat 이 modoverrides.lua 를 고쳐서 모드를 껐다 켰다 합니다.
  시작할 때 원본을 백업해 두고, 끝나면 그대로 되돌립니다.
  중간에 그만두시려면 bisect_UNDO.bat 을 더블클릭하세요. 바로 되돌립니다.

  * 데디케이티드 서버(클러스터 폴더)에서만 씁니다.
  * 도중에 게임 안 모드 화면에서 모드를 건드리면 그 화면이 modoverrides.lua 를
    덮어씁니다. 찾는 동안에는 건드리지 마세요.
  * 먼저 lasterror.bat 을 돌려 보세요. 로그가 이미 범인을 찍어 줬다면
    한 번도 안 켜 보고 끝납니다.


[ 모드를 한국어로 바꾸고 싶을 때 - translate.bat ]

  translate.bat 은 번역할 글자가 든 파일만 골라 담습니다.

  DST 모드의 글자는 딱 세 군데에 있습니다.

    languages/*.po   클레이가 정한 정식 번역 파일. 여기 한국어 po 를 넣는
                     것이 가장 안전합니다. 코드를 한 줄도 안 건드립니다.
    modinfo.lua      모드 목록에 뜨는 이름과 설명.
    .lua 의 STRINGS  po 를 안 쓰는 모드는 코드에 글자를 박아 둡니다.

  이 세 가지만 담고 나머지는 뺍니다. 그래서 collectmods.bat 보다 훨씬
  작습니다. 같이 들어가는 번역대상.txt 에는 모드마다

    지금 무슨 언어인지 / po 가 있는지 / 한국어 po 가 이미 있는지 /
    번역할 항목이 몇 개인지

  가 적혀 있고, 이미 한국어인 모드와 꺼 둔 모드는 따로 빼 둡니다.


[ 모드를 한국어로 - korean.bat ]

  큰 모드는 대부분 한국어 번역을 이미 품고 있습니다. 안 보이는 이유는 하나뿐,
  모드 설정의 언어가 영어로 되어 있어서입니다. 번역할 것이 아니라 켤 것입니다.

  korean.bat 은 모드마다 modinfo.lua 를 읽어 "언어" 설정을 찾고, 그 설정이
  받는 값 중 한국어에 해당하는 것을 골라 modoverrides.lua 에 적습니다.
  설정값 하나를 바꾸는 것이라 모드가 깨질 수 없습니다.

  같이 나오는 한국어켜기.txt 는 모드를 셋으로 나눠 보여 줍니다.

    한국어로 바꿨습니다        설정으로 켜진 것
    설정으로는 못 켜는 모드    한국어 파일은 있는데 고르는 설정이 없음.
                               이런 모드는 게임 언어를 한국어로 두면
                               알아서 따라오는 경우가 많습니다.
    한국어가 아예 없는 모드    이것만 진짜로 번역이 필요합니다.

  되돌리시려면 korean_UNDO.bat 을 더블클릭하세요. 처음 실행할 때 떠 둔 백업으로
  돌려놓습니다 (두 번 실행해도 백업은 덮어쓰지 않습니다).


[ 모드 글자를 한국어로 - hangul.bat ]

  hangul.bat 을 더블클릭하면 한글 패치 모드를 게임에 넣고 켜 줍니다.
  모드 목록에서 따로 켤 필요 없습니다. 게임만 다시 켜면 됩니다.

  모드 8개, 문자열 1224개를 한국어로 바꿉니다.

      937개  景熹家居 JingXi Furniture
      129개  池中木 Pond OceanTree
       60개  DST Coffee and More
       53개  [API] Modded Skins
       22개  Shadow Field Exciter
        9개  Large Chest (HD)
        9개  ActionQueue RB3
        5개  Winona's Porta-base V2

  손대는 것은 두 가지뿐입니다.

      mods\mod_korean_patch\     우리가 만든 폴더. 통째로 넣고 통째로 뺍니다.
      mods\modsettings.lua       표시 사이 한 줄만 넣고 뺍니다.

  다른 모드의 파일은 한 글자도 안 건드립니다. 이 패치는 게임이 이미 읽어
  들인 STRINGS 표에 한국어를 덮어쓸 뿐이라, 번역이 틀려도 글자가 이상해질
  뿐이고 모드나 서버가 멈추지는 않습니다.

  빼시려면 hangul_UNDO.bat 을 더블클릭하세요. 폴더와 그 한 줄만 없앱니다.
  (명령창에서 hangul.bat stop 을 쳐도 같습니다.)

  * 한글이 네모로 보이면 번역이 아니라 글꼴 문제입니다.
    한글 글꼴을 넣어 주는 모드를 같이 켜 두세요.


[ 개인정보 ]

  collect.bat 과 collectmods.bat 은 계정 이름, 스팀 ID, 토큰처럼 보이는
  문자열을 <가림> 으로 바꿔서 담습니다.
"""


def main() -> None:
    if BUILD.exists():
        shutil.rmtree(BUILD)
    (BUILD / "files").mkdir(parents=True)
    (BUILD / "tools").mkdir(parents=True)
    DIST.mkdir(exist_ok=True)

    # The merged Lua file: plain UTF-8, no BOM, LF endings -- exactly like the
    # files already inside NPC Friends.
    lua = build_lua()
    (BUILD / "files" / "npc_hof_cooking.lua").write_bytes(lua.encode("utf-8"))

    # Windows PowerShell 5.1 only decodes a .ps1 as UTF-8 when it has a BOM,
    # and this one contains Korean.
    ps1 = (PATCH / "templates" / "tools" / "patch.ps1").read_text(encoding="utf-8")
    (BUILD / "tools" / "patch.ps1").write_bytes(
        b"\xef\xbb\xbf" + ps1.replace("\n", "\r\n").encode("utf-8")
    )

    # cmd.exe wants CRLF; these two are ASCII-only on purpose.
    # 한글 패치 모드도 같이 담습니다. hangul.bat 이 이것을 mods 폴더로 옮깁니다.
    korean_src = REPO / "korean_patch"
    if korean_src.exists():
        subprocess.run([sys.executable, str(korean_src / "build_korean.py")], check=True,
                       stdout=subprocess.DEVNULL)
        korean_dst = BUILD / "files" / "mod_korean_patch"
        for rel in ("modinfo.lua", "modmain.lua"):
            src = korean_src / rel
            dst = korean_dst / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dst)

    for name in ("install.bat", "restore.bat", "diagnose.bat", "collect.bat", "collectmods.bat", "lasterror.bat", "modcheck.bat", "bisect.bat", "translate.bat", "korean.bat", "hangul.bat"):
        text = (PATCH / "templates" / name).read_text(encoding="utf-8")
        text.encode("ascii")  # fail the build if Korean sneaks in
        (BUILD / name).write_bytes(text.replace("\n", "\r\n").encode("ascii"))

    # 되돌리기용 파일. bisect.bat stop 처럼 뒤에 말을 붙여야 하는 것들은
    # 더블클릭으로는 그 말을 못 붙입니다. 명령창을 열 필요가 없도록
    # "stop 을 붙인 채로 실행하는" 파일을 따로 만들어 둡니다.
    for base, undo, what in (
        ("hangul.bat", "hangul_UNDO.bat", "remove the Korean string patch"),
        ("korean.bat", "korean_UNDO.bat", "put the mod language settings back"),
        ("bisect.bat", "bisect_UNDO.bat", "stop the search and restore modoverrides.lua"),
    ):
        text = (PATCH / "templates" / base).read_text(encoding="utf-8")
        text = text.replace('-Arg "%~1"', '-Arg "stop"')
        text = text.replace(
            "rem ===========================================================================\n",
            "rem ===========================================================================\n"
            f"rem  THIS IS THE UNDO FILE. Double-click it to {what}.\n"
            f"rem  It is {base} with 'stop' already filled in, because double-clicking\n"
            "rem  cannot pass a word to a .bat file.\n"
            "rem ===========================================================================\n",
            1,
        )
        text.encode("ascii")
        (BUILD / undo).write_bytes(text.replace("\n", "\r\n").encode("ascii"))

    (BUILD / "README.txt").write_bytes(
        b"\xef\xbb\xbf" + README.replace("\n", "\r\n").encode("utf-8")
    )

    archive = DIST / f"{PACKAGE_NAME}.zip"
    if archive.exists():
        archive.unlink()

    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(BUILD.rglob("*")):
            if path.is_file():
                zf.write(path, f"{PACKAGE_NAME}/{path.relative_to(BUILD).as_posix()}")

    print(f"built {archive.relative_to(REPO)}  ({archive.stat().st_size:,} bytes)")
    for path in sorted(BUILD.rglob("*")):
        if path.is_file():
            print(f"  {path.stat().st_size:>8,}  {path.relative_to(BUILD).as_posix()}")


if __name__ == "__main__":
    main()
