#!/usr/bin/env python3
"""Build the NPC Friends x Heap of Foods patch package.

Merges the Lua modules that also power the standalone mod into a single drop-in
file for NPC Friends, then assembles the ready-to-run zip:

    NPC_HOF_Patch/
        install.bat            <- double-click this
        restore.bat            <- undo
        diagnose.bat           <- dump the current state to 진단결과.txt
        collect.bat            <- pack everything needed for support into one zip
        collectmods.bat        <- pack the code of every installed mod
        lasterror.bat          <- find why the server will not start
        modcheck.bat           <- list which mods collide with which
        bisect.bat             <- halve the mod list until the culprit is found
        translate.bat          <- collect every mod's text for translating
        korean.bat             <- switch mods to the Korean they already ship
        korean_CHECK.bat       <- show those settings without changing anything
        hangul.bat             <- install the Korean string patch into the game
        README.txt
        files/npc_hof_cooking.lua
        tools/patch.ps1

The package deliberately ships none of NPC Friends' own code. install.bat backs
up the one file it edits and appends a single line to it, so there is nothing of
theirs to redistribute.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PATCH = REPO / "patch"
SCRIPTS = REPO / "npcfriends_hof_cooking" / "scripts"
BUILD = REPO / "build" / "NPC_HOF_Patch"
DIST = REPO / "dist"

PACKAGE_NAME = "NPC_HOF_Patch"

# Order matters: later modules use the locals declared by earlier ones.
MERGE_ORDER = [
    (SCRIPTS / "hofnpc_core.lua", "Core"),
    (SCRIPTS / "hofnpc_slots.lua", "Slots"),
    (SCRIPTS / "hofnpc_variety.lua", "Variety"),
    (SCRIPTS / "hofnpc_stations.lua", "Stations"),
    (SCRIPTS / "hofnpc_search.lua", "Search"),
    (SCRIPTS / "hofnpc_cookware.lua", "Cookware"),
    (SCRIPTS / "hofnpc_diag.lua", "Diag"),
]

# `local Core = require("hofnpc_core")` and friends: inside the merged file the
# locals are already in scope, so these lines must go.
CROSS_REQUIRE = re.compile(r'^\s*local\s+\w+\s*=\s*require\(\s*"hofnpc_[a-z]+"\s*\)\s*$')


def strip_module(path: Path, returns: str) -> str:
    """Drop the cross-module requires and the trailing `return X`."""
    lines = path.read_text(encoding="utf-8").splitlines()

    kept = [line for line in lines if not CROSS_REQUIRE.match(line)]

    trailing = re.compile(rf"^\s*return\s+{re.escape(returns)}\s*$")
    for index in range(len(kept) - 1, -1, -1):
        if trailing.match(kept[index]):
            del kept[index]
            break
    else:
        raise SystemExit(f"{path.name}: could not find `return {returns}`")

    return "\n".join(kept).rstrip() + "\n"


# Every module keeps its own file-scope locals, but the merged file is one
# chunk, so a `local function Slots(...)` in one module quietly shadows the
# `Slots` module table from another and the failure only shows at runtime.
MODULE_SCOPE_LOCAL = re.compile(r"^local\s+(?:function\s+)?(\w+)")


def check_no_shadowing() -> None:
    names = {returns for _, returns in MERGE_ORDER}
    problems = []

    for path, returns in MERGE_ORDER:
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            match = MODULE_SCOPE_LOCAL.match(line)
            if match is None:
                continue
            name = match.group(1)
            if name in names and name != returns and "require(" not in line:
                problems.append(f"{path.name}:{number}: `local {name}` shadows the {name} module")

    if problems:
        raise SystemExit("merged file would shadow a module:\n  " + "\n  ".join(problems))


def build_lua() -> str:
    banner = (
        "-- " + "=" * 74 + "\n"
        f"--  {'':<2}이 파일은 patch/build.py 가 자동으로 만든 파일입니다.\n"
        "--  Generated by patch/build.py -- edit the sources under\n"
        "--  npcfriends_hof_cooking/scripts/ instead of editing this file.\n"
        "-- " + "=" * 74 + "\n\n"
    )

    check_no_shadowing()

    parts = [banner, (PATCH / "header.lua").read_text(encoding="utf-8")]

    for path, returns in MERGE_ORDER:
        parts.append("\n\n" + "-" * 78 + f"\n-- {path.name}\n" + "-" * 78 + "\n\n")
        parts.append(strip_module(path, returns))

    parts.append("\n\n")
    parts.append((PATCH / "install_stub.lua").read_text(encoding="utf-8"))

    return "".join(parts)


README = """\
====================================================================
  NPC Friends x Heap of Foods - 요리 연동 패치
====================================================================

NPC Friends 의 왈리 NPC 가 Heap of Foods 를 비롯한 음식 모드의 요리를
전부 인식하고, 여러 가지 요리를 돌아가며 만들도록 고쳐 줍니다.


[ 무엇이 문제였나 ]

  NPC Friends 는 "왈리가 만들 수 있는 요리" 목록을 모드 안에 손으로
  적어 두었습니다 (scripts/npc/npc_cooking_recipes.lua).
  거기에는 바닐라 요리와 일부 모드 요리만 들어 있어서, Heap of Foods 가
  추가한 200종이 넘는 요리는 창고에 재료가 아무리 많아도 후보에 오르지
  않습니다.

  게다가 요리를 고르는 함수 맨 앞에 "창고에 미트볼이 없으면 무조건
  미트볼부터" 라는 규칙이 박혀 있어서, 같은 요리만 계속 나옵니다.


[ 이 패치가 하는 일 ]

  요리 목록을 200개 더 적어 넣는 대신, 게임에 등록된 요리표를 직접 읽습니다.
  그래서 정상적인 방법(AddCookerRecipe)으로 등록된 음식 모드라면 무엇이든
  자동으로 인식됩니다. 모드가 업데이트로 요리를 더 추가해도 이 패치는
  그대로 두면 됩니다.

  요리를 찾는 길은 세 가지입니다.

    1) 재료가 적혀 있는 요리(card_def)      바로 읽습니다. Heap of Foods 의
                                            248종이 전부 여기 해당합니다.
    2) 요리에게 직접 물어보기               아래 설명.
    3) 조합을 돌려 보기                     남는 것을 줍는 용도.

  여기에 "최근에 만든 요리"와 "이미 창고에 쌓인 요리"에 감점을 주어
  메뉴가 계속 바뀌도록 했습니다.


[ 재료가 안 적힌 모드 요리를 찾는 법 ]

  대부분의 음식 모드는 재료 목록을 적어 두지 않고 판정 함수만 줍니다.

      test = function(cooker, names, tags)
          return (names.corn or names.corn_cooked)
             and tags.sweetener and tags.frozen and tags.frozen >= 2
      end

  조합을 무작정 돌려서 이걸 찾으려면, 재료 종류가 30가지인 창고에서
  4칸짜리 조합이 4만 가지가 나옵니다. 서버가 안 멈추게 하려면 그중 일부만
  볼 수밖에 없고, 그러면 "2~3개밖에 없는 재료" 를 쓰는 요리는 영영 안
  걸립니다. 음식 모드를 갓 깔았을 때가 딱 그 상황입니다.

  그래서 반대로 갑니다. 아직 못 만든 요리를 하나 집어서, 그 요리에게
  "너는 무슨 재료를 보느냐" 고 직접 물어봅니다.

  판정 함수가 names 와 tags 에 할 수 있는 일은 값을 꺼내 보는 것뿐입니다.
  그러니 "꺼내 간 이름을 전부 적어 두는 표" 를 건네주면, 함수가 스스로
  자기 재료 목록을 불러 줍니다. 손으로 적은 표도 없고, 코드를 읽어서
  짐작하는 것도 아니라서, 모드가 업데이트돼도 그대로 맞습니다.

  and 는 거짓이 나오면 거기서 멈추므로 한 번만 물어서는 모자랍니다
  (tags.meat >= 2 로 시작하는 함수는 고기를 2개 이상 줘야 그 뒤를
  보여 줍니다). 그래서 없음 / 1 / 2 / 4 를 섞어 여러 번 물어보고 합칩니다.
  대답은 math.random 이 아니라 이름을 해시해서 정하므로, 서버의 난수를
  건드리지 않고 몇 번을 돌려도 같은 답이 나옵니다.

  실측 (음식 모드 3개, 재료 30종, 모드 요리 37가지):

                   찾아낸 모드 요리    실제로 만든 요리    한 번 계산에
      이전  (보통)        15 / 37             9              22 ms
      지금  (보통)        30 / 37            17              10 ms


[ 설치 ]

  1. 이 zip 을 폴더째 압축 해제합니다. (압축 안에서 바로 실행하면 안 됩니다)
  2. DST 를 완전히 종료합니다.
  3. install.bat 을 더블클릭합니다.
  4. DST 를 다시 실행하고, Heap of Foods 와 NPC Friends 를 둘 다 켠 채로
     월드에 들어갑니다.
  5. 왈리 NPC 에게 냄비와 아이스박스를 지정하고 요리를 시켜 봅니다.

  권한 오류가 나면 install.bat 을 마우스 오른쪽 클릭 ->
  "관리자 권한으로 실행" 을 해 주세요.


[ 되돌리기 ]

  restore.bat 을 더블클릭하면 원래대로 돌아갑니다.
  원본은 설치할 때 _backup 폴더에 보관됩니다.


[ 문제가 생겼을 때 - collect.bat ]

  collect.bat 을 더블클릭하면, 문제를 보는 데 필요한 것만 알아서 골라
  zip 하나로 묶어 줍니다. 그 zip 만 보내 주시면 됩니다.

  담기는 것:
    - 지금 설치 상태 (파일별로 원본인지 / 다른 패치가 고쳤는지 판정)
    - 요리 관련 lua 파일 10개
    - DST 로그에서 요리 관련 줄만 최근 400줄
    - 켜져 있는 모드 목록 (modoverrides.lua)

  계정 이름, 스팀 ID 같은 것은 <가림> 으로 바꿔서 담습니다.

  모드 폴더를 못 찾으면, 3684000581 폴더를 collect.bat 위로
  드래그해서 놓으시면 됩니다.

  로그가 비어 있으면 files\npc_hof_cooking.lua 의 debug 를 true 로
  바꾸고 install.bat 을 다시 실행한 뒤, 게임에서 요리를 몇 번 시켜 보고
  collect.bat 을 실행해 주세요. NPC Friends 자체 요리 로그까지 같이 켜집니다.


[ 설정 바꾸기 ]

  files\\npc_hof_cooking.lua 를 메모장으로 열면 맨 위에 USER_SETTINGS 가
  있습니다. 값을 고친 뒤 install.bat 을 다시 실행하면 적용됩니다.

    variety          요리 다양성   "off" / "low" / "medium" / "high"
    budget           탐색량        "low" / "medium" / "high"
    same_dish_max    같은 요리를 창고에 몇 개까지 쌓을지 (0 = 모드 설정 따름)
    allow_negative   체력/정신력이 깎이는 요리도 만들지 (기본 켜짐)
    taste_everything 한 가지를 두 번 만들기 전에 다른 것을 먼저 만들지 (기본 켜짐)
    spread_cookware  4칸 안 되는 도구는 건너뛰고 냄비를 돌아가며 쓸지 (기본 켜짐)
    explain          요리를 못 할 때 왈리가 그 이유를 직접 말함 (기본 켜짐)
    debug            고른 이유까지 전부 서버 로그에 출력


[ 커피처럼 값어치가 낮은 요리 ]

  왈리 NPC 는 요리의 값어치로 고릅니다 (체력 + 배부름*0.4 + 정신력*0.8).
  그런데 값어치 차이가 너무 큽니다. 재료 30종에 음식 모드 3개를 깔면

      330  만드레이크 요리
      124  달걀 요리
        3  에스프레소  (커피는 원래 정신력을 -5 깎는 것이 컨셉)

  이 상태면 커피는 영원히 안 나옵니다. "새 요리 가산점" 을 아무리 줘도
  327점 차이를 뒤집을 수는 없습니다.

  그래서 taste_everything 이 있습니다. 아직 한 번도 안 만든 요리가 남아
  있으면 그것부터 만듭니다. 한 바퀴 돌고 나면 다시 값어치 순으로
  돌아갑니다. 창고에 같은 것 4개보다 여러 가지가 하나씩 있는 쪽이
  낫기도 하고요.

  allow_negative 와 같이 켜져 있어야 커피가 나옵니다. 둘 다 기본값입니다.


[ 왈리의 휴대용 양념기를 냄비로 착각하는 문제 ]

  NPC Friends 는 근처에서 "stewer" 표가 붙은 것을 전부 냄비로 봅니다.
  그 표는 stewer 부품이 스스로 붙이는 것이라(scripts/components/stewer.lua),
  왈리의 휴대용 양념기도 같이 걸려듭니다.

  양념기는 칸이 2개뿐이고, 1번 칸은 "요리된 음식", 2번 칸은 "향신료" 만
  받습니다(scripts/containers.lua). 생재료는 아예 안 들어갑니다.
  그런데 왈리 NPC 는 언제나 4칸짜리 요리를 계획하고, 재료 4개를 안 들고
  있으면 포기하게 되어 있습니다.

  즉 냄비 옆에 양념기를 놓아 두면 — 왈리를 쓰는 사람은 거기 놓습니다 —
  NPC 가 양념기로 걸어가서 아무것도 못 넣고 요리에 실패합니다.

  spread_cookware 가 그것을 막습니다. 4칸이 안 되는 도구는 냄비 후보에서
  빼고, 쓸 수 있는 냄비가 여러 개면 돌아가며 씁니다.
  다 만든 음식을 거두는 것은 그대로입니다. NPC Friends 의 수확 단계는
  이 함수를 거치지 않고 목록을 직접 보기 때문입니다.


[ 양념기 쓰게 하기 - use_spicer ]

  양념기를 피하는 것으로 끝내지 않고, 실제로 쓰게 했습니다.
  요리된 음식 + 향신료 → 양념 요리 (마늘가루=피해감소, 고춧가루=공격력,
  설탕=작업속도, 소금=맛).

  막고 있던 것은 두 가지였습니다.
    1) 재료를 4개 안 들고 있으면 양념기로 걸어가지 않는다
    2) 4개를 안 넣었으면 불을 안 붙인다
  둘 다 난독화된 행동 파일 안에 있습니다.

  그런데 그 파일이 쓰는 NPCCookingBehavior 는 그냥 전역 클래스이고,
  문제의 두 단계가 그 클래스의 함수로 나와 있습니다.

      NPCCookingBehavior:_MakeTakeActionFn(items, taken)
      NPCCookingBehavior:_MakePutActionFn(taken, plan, node)

  앞의 것이 돌려주는 함수가 상자에서 물건을 꺼내 taken 에 이름을 적는데,
  4개 검사는 바로 그 taken 의 길이를 셉니다. 뒤의 것이 냄비에 넣고 불을
  붙입니다. 이 둘만 감싸면 됩니다. 남의 코드를 베끼거나 다시 구현하지
  않고, 일반 요리일 때는 그대로 통과시킵니다.

  양념 요리는 찾을 것도 없습니다. DST 의 양념 레시피 440개(바닐라 316 +
  음식 모드 124)가 전부 자기 재료를 적어 두고 있습니다.

      name     = "meatballs_spice_garlic"
      basename = "meatballs"
      spice    = "SPICE_GARLIC"

  * 요리와 번갈아 합니다. 양념만 하면 창고가 안 찹니다.
  * 양념기가 계속 거부하면 세 번 만에 포기하고 원래대로 돌아갑니다.
  * NPCCookingBehavior 가 없거나 모양이 달라지면 연결을 포기합니다.
    그때는 양념기를 피하기만 하던 지금까지의 동작이 됩니다.


[ 건조대 쓰게 하기 - use_dryer ]

  고기와 버섯을 건조대에 널어 말린 고기 / 말린 버섯을 만듭니다.
  안 상하고 오래 가는 비상식량이 알아서 쌓입니다.
  Heap of Foods 를 쓰시면 말릴 수 있는 것이 훨씬 많아집니다.

  건조대는 냄비와 많이 다릅니다.

    칸이 없습니다            한 개를 그냥 위에 올립니다
    쓰는 말이 다릅니다       CanDry / StartDrying / IsDrying
                             (냄비는 CanCook / StartCooking / IsCooking)
    표가 안 달려 있습니다    NPC Friends 는 "stewer" 표로 냄비를 찾는데
                             건조대에는 그 표가 없어서 목록에 안 뜹니다

  그래서 건조대를 "냄비처럼 대답하는 대역"으로 감싸서 넘깁니다. 위치·유효성·
  표는 진짜 건조대에게 물어보고, stewer 자리에는 건조 부품을 감싼 어댑터를
  놓습니다. 이 대역은 행동 파일만 들고 있습니다 —
  **세상에 있는 진짜 건조대에는 없는 부품을 붙이지 않습니다.**
  그래서 다른 모드도, 세이브 파일도 이것을 보지 못합니다.

  넣는 순서는 바닐라 DRY 행동 그대로입니다 (actions.lua).
    CanDry 확인 -> 요리사 가방에서 빼기 -> StartDrying
  StartDrying 이 성공하면 아이템 자체를 없앱니다(dryer.lua 의 dryable:Remove()).
  실패하면 가방에 도로 넣습니다. 음식이 사라지지 않습니다.

  * 양념기가 있으면 양념기를 먼저 씁니다. 이미 만든 요리에 양념을 하는 쪽이
    아직 요리할 수 있는 재료를 말리는 것보다 낫기 때문입니다.
  * 실패 횟수는 기구 종류마다 따로 셉니다. 건조대가 말을 안 들어도
    양념기와 통은 계속 돌아갑니다.


[ 통·항아리에 담그게 하기 - use_brewer ]

  Heap of Foods 의 나무통과 저장 항아리에 술과 저장식품을 담급니다.
  와인은 3일, 어떤 것은 20일씩 걸립니다. 한 번 담가 두면 알아서 익습니다.

  양조는 요리와 완전히 다른 체계입니다 (scripts/hof_brewing.lua).
  Klei 의 cooking 을 거의 그대로 베낀 별도 모듈이라

      brewing.recipes[기구][결과물]      요리표가 따로
      brewing.brewingredients             재료표도 따로
      brewing.CalculateBrewing            판정도 따로 (역시 math.random 으로 끝남)

  그래서 요리 쪽 재료 검색에는 통 재료가 아예 안 보입니다. 따로 훑습니다.

  다행히 양조 레시피는 자기 재료를 적어 두고 있어서 찾을 것이 없습니다.

      wine_berries = { card_def = { ingredients = {{"berries", 2}, {"ice", 1}} } }

  결과물을 정하는 방법도 같습니다. Brewer:StartCooking 이 모듈 표를 통해
  brewing.CalculateBrewing 을 부르므로, 부르는 동안만 그 칸을 바꿔 두었다가
  되돌립니다. NPC Friends 가 cooking.CalculateRecipe 에 하는 것과 같습니다.
  덕분에 통이 제멋대로 뽑지 않고, 월드 난수도 안 건드립니다.

  * 통은 꽉 차야 시작됩니다. 그래서 재료 수가 칸 수와 정확히 맞는
    레시피만 고릅니다. 안 맞는 것은 아무도 못 만드는 레시피입니다.
  * 양념기 -> 통 -> 건조대 순으로 봅니다. 통은 며칠씩 걸리니 일찍
    담가 두는 편이 낫고, 건조는 아무 때나 해도 되기 때문입니다.
  * Heap of Foods 가 없으면 알아서 아무것도 안 합니다.


[ 젖 짜게 하기 - use_milker ]

  비팔로 / 코알레펀트 / 번개염소 에게서 젖을 짭니다. 각각 다른 젖이 나오고,
  봄에는 하나 더, 길들인 비팔로는 둘 더 나옵니다.

  이건 기구가 아닙니다. 담을 통도, 익는 시간도, 나중에 거둘 것도 없습니다.
  ACTIONS.PULLMILK 은 한 번 부르면 젖이 바로 손에 들어오는 함수입니다
  (hof_actions.lua:233).

      act.target.components.milkableanimal:Milk(act.doer)
      if act.invobject.components.finiteuses then finiteuses:Use(1) end

  그래서 그대로 합니다. 양동이도 진짜로 들고 가고 내구도도 실제로 씁니다.
  요리사가 젖을 공짜로 만들어내지 않습니다. 양동이가 없으면 아무 일도
  일어나지 않습니다 (테스트 있음).

  * 동물은 걸어다닙니다. 요리사는 "아까 본 자리" 로 출발해서, 도착했을 때
    없으면 포기합니다. 야생 비팔로는 자주 놓칩니다.
    묶어 두었거나 길들인 동물이 훨씬 잘 되고, 양도 두 배 가까이 나옵니다.

  * Heap of Foods 의 CanBeMilked() 는 쓸 수 없습니다. self.canbemilked 가
    아니라 그냥 canbemilked 라는 전역을 읽어서, 살아있는 모든 동물에 대해
    nil 을 돌려줍니다 (milkableanimal.lua:119). 그래서 Milk() 가 스스로
    확인하는 조건을 대신 봅니다.


[ 왈리가 "재료가 없어요" 라고 할 때 ]

  왈리는 창고 전체를 보지 않습니다. '여기서 요리' 로 지정한 지점 기준
  반경 약 17칸 안에 있는, 아이스박스/상자류만 봅니다.

  이 패치를 깔면 왈리가 왜 못 하는지 직접 말해 줍니다. 예를 들어

    "상자 3개를 봤는데 요리 재료가 없어요. 제 상자에 넣어 주세요."
    "요리 지점 근처에 냄비가 없어요."
    "가방이 꽉 차서 재료를 못 들어요."
    "재료는 12종 있는데 만들 수 있는 요리가 없어요."

  가장 흔한 원인은 첫 번째입니다. 왈리는 자기가 지은 아이스박스 1개와
  나무상자 2개를 씁니다. 재료를 그 3개 안에 넣어 주시거나,
  재료 상자 옆에서 '여기서 요리' 를 다시 지정해 주세요.

  마지막 줄이 나오면 '같은 요리 최대 개수' 를 올려 보세요.
  이미 만들 수 있는 요리를 전부 상한까지 쌓아 둔 상태일 수 있습니다.


[ 알아두실 점 ]

  * Steam 이 NPC Friends 를 업데이트하면 이 패치는 지워집니다.
    그때는 install.bat 을 다시 한 번 실행해 주세요.

  * 멀티에서는 서버(호스트) 쪽에 설치되어 있어야 효과가 있습니다.
    NPC 의 요리 판단은 전부 서버에서 이루어지기 때문입니다.

  * 건드리는 파일은 scripts/npc/npc_cooking_planner.lua 하나뿐이고,
    그것도 맨 끝에 아래 한 줄을 넣는 것이 전부입니다.

      pcall(function() require("npc/npc_hof_cooking").Install(CookingPlanner) end)

  * 문제가 생기면 USER_SETTINGS 의 debug 를 true 로 바꾸고 서버 로그의
    [NPCF-HOF] 줄을 확인해 주세요.


[ 문제가 생겼을 때 - collect.bat ]

  collect.bat 을 더블클릭하면, 이 패치와 관련된 것만 골라 zip 하나로
  묶어 줍니다. 설치 상태 판정, 요리 관련 lua 10개, 로그의 요리 관련 줄,
  켜져 있는 모드 목록이 들어갑니다.

  diagnose.bat 은 같은 내용을 압축 없이 진단결과.txt 로만 뽑습니다.


[ 설치된 모드를 전부 보내고 싶을 때 - collectmods.bat ]

  collectmods.bat 은 설치된 모든 DST 모드의 "코드"만 골라 담습니다.

  모드 폴더를 통째로 압축하면 보통 수 GB 입니다. 대부분이 애니메이션(.zip),
  텍스처(.tex), 사운드(.fsb/.fev) 라서 문제를 보는 데는 쓸모가 없습니다.
  실측으로 모드 2개 199 MB 가 3.8 MB 가 됩니다.

    담는 것   .lua .json .xml .txt .md .po .ini .cfg
    빼는 것   anim/ sound/ images/ bigportraits/ exported/ minimap/
              levels/textures/ levels/tiles/ 와 3 MB 넘는 파일

  모드를 하나도 못 담았더라도, 모든 모드는 모드목록.txt 에 반드시 나옵니다
  (이름 / 버전 / api / 파일 수 / 진짜 용량).

  모드를 못 찾으면 모드가 들어 있는 폴더를 collectmods.bat 위로 드래그하세요.
  보통 이 경로입니다:

    ...\\steamapps\\workshop\\content\\322330


[ 어떤 모드가 문제인지 알고 싶을 때 - modcheck.bat ]

  modcheck.bat 을 더블클릭하면, 설치된 모드의 lua 를 전부 읽어서
  모드끼리 부딪칠 수 있는 지점만 골라 모드점검.txt 로 뽑아 줍니다.

    1  서버가 안 켜지게 만들 수 있는 것
       WX-78 모듈 자리 계산. 바닐라 wx78_moduledefs.lua 안에
         assert(module_netid < 64, "To support additional WX modules, ...")
       가 있고 바닐라가 23 개를 먼저 씁니다. 모드 몫은 40 개뿐이라,
       넘기면 서버가 통째로 안 켜집니다. 어느 모드가 몇 개를 쓰는지 셉니다.
       오류 화면을 자기 코드로 바꾸는 모드도 여기서 짚습니다. 그런 모드가
       있으면 다른 모드의 사소한 오류 하나가 "서버 시작 실패" 로 커집니다.

    2  왈리 요리에 끼어들 수 있는 모드
       상자 내부, 냄비, 요리 계산식을 건드리는 모드. 그리고 같은 냄비 요리
       이름을 두 모드가 동시에 쓰는 경우 (나중에 켜진 쪽만 남습니다).

    3  로그가 직접 이름을 부른 모드
       가장 확실한 증거입니다. 최근 로그에서 MOD ERROR 로 찍혔거나
       오류 스택에 그 모드 파일이 나온 것만 추립니다.

    4  참고
       낡은 api_version, 서버에선 아무 일도 안 하는 client_only 모드,
       서버에 켜 놓았는데 설치가 안 된 모드.

  modoverrides.lua 를 찾으면 "서버에 켜져 있는 모드"만 계산에 넣습니다.
  구독만 해 놓고 꺼 둔 모드는 아무 자리도 차지하지 않기 때문입니다.

  모드를 못 찾으면 모드가 들어 있는 폴더를 modcheck.bat 위로 드래그하세요.


[ 서버가 아예 안 켜질 때 - lasterror.bat ]

  "데디케이티드 서버 시작 실패" 가 뜨면 lasterror.bat 을 더블클릭하세요.
  가장 최근 로그에서 진짜 오류 줄만 찾아 앞뒤 문맥까지 같이 뽑아
  서버오류.txt 로 저장하고, 화면에도 그대로 보여 줍니다.

  거의 항상 원인은 모드 하나입니다. 오류 줄에 나오는
  workshop-<숫자> 가 범인이고, 그 모드를 끄면 켜집니다.


[ 서버가 안 켜지는데 로그로도 모르겠을 때 - bisect.bat ]

  로그가 모드 이름을 안 찍어 주는 경우가 있습니다. 그때 씁니다.

  켜져 있는 모드를 절반씩 잘라 가며, 어느 쪽에 범인이 있는지 좁힙니다.
  모드 48 개면 48 번이 아니라 열 번 안쪽이면 끝납니다. 두 모드가 "같이
  켜져 있을 때만" 터지는 경우도 찾습니다 (그건 스무 번쯤 걸립니다).

  쓰는 법은 이것뿐입니다:

    1  bisect.bat 실행
    2  서버를 켜 본다 (켜지든 안 켜지든 상관없음)
    3  bisect.bat 다시 실행
    4  범인 이름이 나올 때까지 2~3 반복

  bisect.bat 이 modoverrides.lua 를 고쳐서 모드를 껐다 켰다 합니다.
  시작할 때 원본을 백업해 두고, 끝나면 그대로 되돌립니다.
  중간에 그만두시려면 bisect_UNDO.bat 을 더블클릭하세요. 바로 되돌립니다.

  * 데디케이티드 서버(클러스터 폴더)에서만 씁니다.
  * 도중에 게임 안 모드 화면에서 모드를 건드리면 그 화면이 modoverrides.lua 를
    덮어씁니다. 찾는 동안에는 건드리지 마세요.
  * 먼저 lasterror.bat 을 돌려 보세요. 로그가 이미 범인을 찍어 줬다면
    한 번도 안 켜 보고 끝납니다.


[ 모드를 한국어로 바꾸고 싶을 때 - translate.bat ]

  translate.bat 은 번역할 글자가 든 파일만 골라 담습니다.

  DST 모드의 글자는 딱 세 군데에 있습니다.

    languages/*.po   클레이가 정한 정식 번역 파일. 여기 한국어 po 를 넣는
                     것이 가장 안전합니다. 코드를 한 줄도 안 건드립니다.
    modinfo.lua      모드 목록에 뜨는 이름과 설명.
    .lua 의 STRINGS  po 를 안 쓰는 모드는 코드에 글자를 박아 둡니다.

  이 세 가지만 담고 나머지는 뺍니다. 그래서 collectmods.bat 보다 훨씬
  작습니다. 같이 들어가는 번역대상.txt 에는 모드마다

    지금 무슨 언어인지 / po 가 있는지 / 한국어 po 가 이미 있는지 /
    번역할 항목이 몇 개인지

  가 적혀 있고, 이미 한국어인 모드와 꺼 둔 모드는 따로 빼 둡니다.


[ 모드를 한국어로 - korean.bat ]

  큰 모드는 대부분 한국어 번역을 이미 품고 있습니다. 안 보이는 이유는 하나뿐,
  모드 설정의 언어가 영어로 되어 있어서입니다. 번역할 것이 아니라 켤 것입니다.

  korean.bat 은 모드마다 modinfo.lua 를 읽어 "언어" 설정을 찾고, 그 설정이
  받는 값 중 한국어에 해당하는 것을 골라 modoverrides.lua 에 적습니다.
  설정값 하나를 바꾸는 것이라 모드가 깨질 수 없습니다.

  같이 나오는 한국어켜기.txt 는 모드를 다섯으로 나눠 보여 줍니다.

    한국어로 바꿨습니다        설정으로 켜진 것. 바꾸기 전 값도 같이 적습니다.
    이미 한국어              손댈 것이 없던 것
    modoverrides 에 없음     이 클러스터에서 안 켜져 있거나 블록이 아직 없음
    설정으로는 못 켜는 모드    한국어 파일은 있는데 고르는 설정이 없음.
                               이런 모드는 게임 언어를 한국어로 두면
                               알아서 따라오는 경우가 많습니다.
    한국어가 아예 없는 모드    이것만 진짜로 번역이 필요합니다.

  고치기 전에 지금 상태만 보고 싶으면 korean_CHECK.bat 을 더블클릭하세요.
  파일은 한 글자도 안 건드리고 한국어상태.txt 만 뽑습니다.

  되돌리시려면 korean_UNDO.bat 을 더블클릭하세요. 처음 실행할 때 떠 둔 백업으로
  돌려놓습니다 (두 번 실행해도 백업은 덮어쓰지 않습니다).


  [ 게임 안 모드 설정에서 바꿔도 안 되는 이유 ]

  목록에 [서버 설정이 접속자에게도 내려감] 이라고 붙는 모드가 있습니다.
  modinfo 에 all_clients_require_mod = true 라고 적힌 모드들입니다.

  이런 모드는 서버에 접속하는 순간 서버가 자기 설정을 통째로 내려보내고,
  내 게임은 그것을 그대로 씁니다. 그래서 게임 안 모드 설정 화면에서 혼자
  언어를 한국어로 바꿔 놔도 접속하면 다시 서버 값으로 덮입니다.
  (Klei 의 networking.lua DownloadMods 가 SetTempModConfigData 를 부르고,
   modindex.lua 의 GetModConfigurationOptions_Internal 이 temp_enabled 인
   모드에 대해 그 값을 돌려줍니다.)

  즉 이런 모드는 modoverrides.lua 가 전부입니다. korean.bat 을 돌리고
  서버를 다시 켜야 바뀝니다.


[ 모드 글자를 한국어로 - hangul.bat ]

  hangul.bat 을 더블클릭하면 한글 패치 모드를 게임에 넣고 켜 줍니다.
  모드 목록에서 따로 켤 필요 없습니다. 게임만 다시 켜면 됩니다.

  모드 8개, 문자열 1224개를 한국어로 바꿉니다.

      937개  景熹家居 JingXi Furniture
      129개  池中木 Pond OceanTree
       60개  DST Coffee and More
       53개  [API] Modded Skins
       22개  Shadow Field Exciter
        9개  Large Chest (HD)
        9개  ActionQueue RB3
        5개  Winona's Porta-base V2

  손대는 것은 두 가지뿐입니다.

      mods\mod_korean_patch\     우리가 만든 폴더. 통째로 넣고 통째로 뺍니다.
      mods\modsettings.lua       표시 사이 한 줄만 넣고 뺍니다.

  다른 모드의 파일은 한 글자도 안 건드립니다. 이 패치는 게임이 이미 읽어
  들인 STRINGS 표에 한국어를 덮어쓸 뿐이라, 번역이 틀려도 글자가 이상해질
  뿐이고 모드나 서버가 멈추지는 않습니다.

  빼시려면 hangul_UNDO.bat 을 더블클릭하세요. 폴더와 그 한 줄만 없앱니다.
  (명령창에서 hangul.bat stop 을 쳐도 같습니다.)

  * 한글이 네모로 보이면 번역이 아니라 글꼴 문제입니다.
    한글 글꼴을 넣어 주는 모드를 같이 켜 두세요.


[ 직접 만들어서 상자에 넣어 두신 것 ]

  Mealing Stone(맷돌) 은 조리 기구가 아니라 제작대(prototyper)라서 요리사가
  쓸 수 없습니다. 하지만 **직접 갈아서 상자에 넣어 두시면 요리사가 씁니다.**
  따로 설정할 것 없습니다.

  이유는 간단합니다. NPC Friends 가 "이게 요리 재료냐" 를 판정하는 방법은
  딱 하나, cooking.IsCookingIngredient(prefab) 입니다. 그리고 Heap of Foods 는
  맷돌 산물 7가지를 전부 평범한 AddIngredientValues 로 등록합니다.
  당근이 재료인 것과 똑같은 이유로 재료입니다.

      kyno_flour                 flour=1, inedible=1
      kyno_spotspice             spotspice=1
      kyno_salt                  inedible=1
      kyno_bacon                 bacon=1, meat=0.5
      kyno_oil                   oil=1
      kyno_sugar                 sugar=1, sweetener=1
      kyno_opalpreciouspowder    precious=1, sugar=2

  (맷돌 조합법은 14개지만 _w 가 붙은 7개는 왈리 전용 조합법이고 나오는
   물건은 같습니다.)

  이걸 넣어 두면 Heap of Foods 요리 412개 중 상당수가 열립니다.

      spotspice 를 쓰는 요리   93개
      flour 를 쓰는 요리       77개
      kyno_salt 를 쓰는 요리   49개
      kyno_sugar / sugar       44개
      oil                      18개
      bacon                    9개

  같은 이야기가 다른 것에도 그대로 적용됩니다. 어떤 모드든 정상적인 방법으로
  등록한 재료라면 상자에 넣어 두기만 하면 됩니다.

      요리 재료      AddIngredientValues 로 등록된 것 전부
      향신료         "spice" 표가 붙은 것
      말릴 것        dryable 부품이 있는 것
      통 재료        brewing 쪽에 등록된 것
      양동이         "bucket" 표 + milker 부품

  요리사가 목록을 따로 들고 있지 않습니다. 게임에 물어봅니다.


[ 개인정보 ]

  collect.bat 과 collectmods.bat 은 계정 이름, 스팀 ID, 토큰처럼 보이는
  문자열을 <가림> 으로 바꿔서 담습니다.
"""


def main() -> None:
    if BUILD.exists():
        shutil.rmtree(BUILD)
    (BUILD / "files").mkdir(parents=True)
    (BUILD / "tools").mkdir(parents=True)
    DIST.mkdir(exist_ok=True)

    # The merged Lua file: plain UTF-8, no BOM, LF endings -- exactly like the
    # files already inside NPC Friends.
    lua = build_lua()
    (BUILD / "files" / "npc_hof_cooking.lua").write_bytes(lua.encode("utf-8"))

    # Windows PowerShell 5.1 only decodes a .ps1 as UTF-8 when it has a BOM,
    # and this one contains Korean.
    ps1 = (PATCH / "templates" / "tools" / "patch.ps1").read_text(encoding="utf-8")
    (BUILD / "tools" / "patch.ps1").write_bytes(
        b"\xef\xbb\xbf" + ps1.replace("\n", "\r\n").encode("utf-8")
    )

    # cmd.exe wants CRLF; these two are ASCII-only on purpose.
    # 한글 패치 모드도 같이 담습니다. hangul.bat 이 이것을 mods 폴더로 옮깁니다.
    korean_src = REPO / "korean_patch"
    if korean_src.exists():
        subprocess.run([sys.executable, str(korean_src / "build_korean.py")], check=True,
                       stdout=subprocess.DEVNULL)
        korean_dst = BUILD / "files" / "mod_korean_patch"
        for rel in ("modinfo.lua", "modmain.lua"):
            src = korean_src / rel
            dst = korean_dst / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dst)

    for name in ("install.bat", "restore.bat", "diagnose.bat", "collect.bat", "collectmods.bat", "lasterror.bat", "modcheck.bat", "bisect.bat", "translate.bat", "korean.bat", "hangul.bat"):
        text = (PATCH / "templates" / name).read_text(encoding="utf-8")
        text.encode("ascii")  # fail the build if Korean sneaks in
        (BUILD / name).write_bytes(text.replace("\n", "\r\n").encode("ascii"))

    # 되돌리기용 파일. bisect.bat stop 처럼 뒤에 말을 붙여야 하는 것들은
    # 더블클릭으로는 그 말을 못 붙입니다. 명령창을 열 필요가 없도록
    # "stop 을 붙인 채로 실행하는" 파일을 따로 만들어 둡니다.
    for base, made, word, what in (
        ("hangul.bat", "hangul_UNDO.bat", "stop", "remove the Korean string patch"),
        ("korean.bat", "korean_UNDO.bat", "stop", "put the mod language settings back"),
        ("bisect.bat", "bisect_UNDO.bat", "stop", "stop the search and restore modoverrides.lua"),
        ("korean.bat", "korean_CHECK.bat", "check", "see what the mod language settings are right now, changing nothing"),
    ):
        text = (PATCH / "templates" / base).read_text(encoding="utf-8")
        text = text.replace('-Arg "%~1"', f'-Arg "{word}"')
        text = text.replace(
            "rem ===========================================================================\n",
            "rem ===========================================================================\n"
            f"rem  Double-click this to {what}.\n"
            f"rem  It is {base} with '{word}' already filled in, because double-clicking\n"
            "rem  cannot pass a word to a .bat file.\n"
            "rem ===========================================================================\n",
            1,
        )
        text.encode("ascii")
        (BUILD / made).write_bytes(text.replace("\n", "\r\n").encode("ascii"))

    (BUILD / "README.txt").write_bytes(
        b"\xef\xbb\xbf" + README.replace("\n", "\r\n").encode("utf-8")
    )

    archive = DIST / f"{PACKAGE_NAME}.zip"
    if archive.exists():
        archive.unlink()

    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(BUILD.rglob("*")):
            if path.is_file():
                zf.write(path, f"{PACKAGE_NAME}/{path.relative_to(BUILD).as_posix()}")

    print(f"built {archive.relative_to(REPO)}  ({archive.stat().st_size:,} bytes)")
    for path in sorted(BUILD.rglob("*")):
        if path.is_file():
            print(f"  {path.stat().st_size:>8,}  {path.relative_to(BUILD).as_posix()}")


if __name__ == "__main__":
    main()
