-- modmain.lua  --  자동 생성 파일. 직접 고치지 마세요.
--
-- 모드 8개, 문자열 1224개.
--
-- 이 파일이 지켜야 할 것은 하나입니다: 무슨 일이 있어도 게임이 켜지는 것을
-- 막지 않는다. 글자를 바꾸는 일이 게임을 못 켜게 만들면 아무 의미가 없습니다.
-- 그래서
--   * 다른 파일을 부르지 않습니다 (modimport 실패할 일이 없음)
--   * 전역 변수를 새로 만들지 않습니다 (strict.lua 에 걸릴 일이 없음)
--   * 설정을 읽지 않습니다 (설정이 없을 때 터질 일이 없음)
--   * 모드 한 개씩 pcall 로 감쌉니다 (하나가 실패해도 나머지는 적용됨)
--   * 전체를 다시 pcall 로 감쌉니다 (그래도 실패하면 조용히 아무것도 안 함)

-- DST 의 모드 환경(mods.lua 의 CreateEnvironment)은 메타테이블이 없는 평평한
-- 표입니다. 그 표에 든 이름만 보입니다: pairs, ipairs, print, math, table,
-- type, string, tostring, require, Class, TUNING, GLOBAL, modname, MODROOT.
-- pcall 도 select 도 error 도 거기 없습니다. 그냥 쓰면 nil 을 부르게 되고
-- 그 자리에서 모드가 죽습니다. 그래서 GLOBAL 에서 직접 꺼내 씁니다.
local pcall = GLOBAL.pcall
local select = GLOBAL.select
local type = GLOBAL.type

local function Translate()
	local STRINGS = GLOBAL.STRINGS
	local Index = GLOBAL.KnownModIndex

	-- 그 모드가 실제로 켜져 있을 때만 덮어씁니다. 안 쓰는 모드의 이름을
	-- 미리 심어 두면 다른 모드와 부딪칠 수 있습니다.
	local function Apply(id)
		local ok, enabled = pcall(function()
			return Index:IsModEnabled("workshop-" .. id)
				or Index:IsModForceEnabled("workshop-" .. id)
		end)
		return ok and enabled or false
	end

	-- 글자 하나를 제자리에 넣습니다.
	--
	-- 중간 칸이 이미 "문자열"인 경우를 반드시 따로 다뤄야 합니다. DST 는
	-- STRINGS.ACTIONS.PICK 처럼 동작 문구를 그냥 문자열로 둡니다. 거기에
	-- 대상별 문구를 붙이려면 표로 바꾸고 원래 문자열을 GENERIC 으로 옮기는
	-- 것이 DST 의 규칙입니다. 이 과정을 건너뛰고 문자열에 [...] 로 대입하면
	-- "attempt to index a string value" 로 그 자리에서 터집니다.
	local function Set(value, ...)
		local node = STRINGS
		local n = select("#", ...)

		for i = 1, n - 1 do
			local key = select(i, ...)
			local nxt = node[key]

			if nxt == nil then
				nxt = {}
				node[key] = nxt
			elseif type(nxt) == "string" then
				nxt = { GENERIC = nxt }
				node[key] = nxt
			elseif type(nxt) ~= "table" then
				return      -- 표도 문자열도 아니면 건드리지 않습니다
			end

			node = nxt
		end

		node[select(n, ...)] = value
	end

	-- 남의 표를 고칠 때 씁니다.
	--
	-- Set 과 다르게 표를 만들지 않고 없는 칸을 새로 만들지도 않습니다.
	-- 이미 문자열이 들어 있는 자리만 바꿉니다. 그 모드가 안 깔려 있거나,
	-- 업데이트로 모양이 바뀌었으면 아무 일도 일어나지 않습니다.
	-- 우리 것이 아닌 표에는 그게 맞는 답입니다.
	local function Replace(root, value, ...)
		if type(root) ~= "table" then
			return
		end

		local node = root
		local n = select("#", ...)

		for i = 1, n - 1 do
			node = node[select(i, ...)]
			if type(node) ~= "table" then
				return
			end
		end

		local key = select(n, ...)
		if type(node[key]) == "string" then
			node[key] = value
		end
	end

	-- 다른 모드의 lua 모듈을 가져옵니다. 없으면 nil 입니다.
	local function Module(name)
		local ok, mod = pcall(require, name)
		if ok and type(mod) == "table" then
			return mod
		end
		return nil
	end


	-- JingXi Furniture  (workshop-3597024951)  937개
	pcall(function() if Apply("3597024951") then
		Set("목욕하기", "ACTIONS", "BATH")
		Set("카펫 깔기", "ACTIONS", "DEPLOY", "JX_DEPLOY")
		Set("불어서 끄기", "ACTIONS", "EXTINGUISH_LAMP2")
		Set("분해하기", "ACTIONS", "GIVE", "DISMANTLE")
		Set("교환하기", "ACTIONS", "GIVE", "EXCHANGE")
		Set("수선하기", "ACTIONS", "GIVE", "SEW")
		Set("세탁하기", "ACTIONS", "GIVE", "WASH")
		Set("연료 넣기", "ACTIONS", "JX_ADDFUEL")
		Set("얼음 넣기", "ACTIONS", "JX_AIR_ADDFUEL")
		Set("불 켜기", "ACTIONS", "JX_BACKPACK_LIGHT")
		Set("바르기", "ACTIONS", "JX_BAGUETTE_TRADE")
		Set("도색하기", "ACTIONS", "JX_CAR_COLOUR")
		Set("수리하기", "ACTIONS", "JX_CAR_REPAIR")
		Set("마시기", "ACTIONS", "JX_DRINK")
		Set("운전하기", "ACTIONS", "JX_DRIVE")
		Set("꽃 장식하기", "ACTIONS", "JX_FLOWERCART_DECOR")
		Set("끌기", "ACTIONS", "JX_HANDCART_PULL")
		Set("잠자기", "ACTIONS", "JX_HANGING_BED")
		Set("부여하기", "ACTIONS", "JX_IMMORTALABLE")
		Set("충전하기", "ACTIONS", "JX_MEDALRECHARGE")
		Set("동승하기", "ACTIONS", "JX_PASSENGER")
		Set("씻기", "ACTIONS", "JX_REFRESH")
		Set("구매하기", "ACTIONS", "JX_SHOPPING")
		Set("내리기", "ACTIONS", "JX_STOPDRIVE")
		Set("테이프 넣기", "ACTIONS", "JX_TAPE_GIVE")
		Set("테이프 보기", "ACTIONS", "JX_TAPE_OPEN")
		Set("버리기", "ACTIONS", "JX_TRASH_CAN_DROP")
		Set("연주하기", "ACTIONS", "JX_TURNON_PIANO")
		Set("잠금 풀기", "ACTIONS", "JX_UNLOCK_SAFE")
		Set("세탁하기", "ACTIONS", "JX_WASHER")
		Set("가져오기", "ACTIONS", "PICK", "TAKEITEM")
		Set("밀기", "ACTIONS", "START_PUSHING", "JX_PUSH_1")
		Set("밀기 한 번 밀고 나면 끌 수 있다", "ACTIONS", "START_PUSHING", "JX_PUSH_2")
		Set("기록하기", "ACTIONS", "TEACH", "RECORD")
		Set("평범한 기사가 입는 얇은 철판 갑옷.", "CHARACTERS", "GENERIC", "DESCRIBE", "ARMOR_JX_KNIGHT")
		Set("메이드 징시 아가씨의 조각상을 만들었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "CHESSPIECES_JX")
		Set("징시 아가씨를 조각상으로 만들었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "CHESSPIECE_JX")
		Set("받침에 이렇게 새겨져 있다. 들려주오, 뮤즈여, 그 총명하고 슬기로운 인간의 이야기를.", "CHARACTERS", "GENERIC", "DESCRIBE", "CHESSPIECE_JX2")
		Set("시원함을 즐긴다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_AIR_CONDITIONER")
		Set("현재 온도 :", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_AIR_CONDITIONER1")
		Set("°C.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_AIR_CONDITIONER2")
		Set("이 방 정말 시원하다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_AIR_CONDITIONER3")
		Set("얼음이 다 떨어졌다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_AIR_CONDITIONER_NOFUEL")
		Set("많이 담을 수 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BACKPACK")
		Set("많이 담을 수 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BACKPACK_2")
		Set("삼색 고양이 인형을 중심으로 만든 양어깨 배낭.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BACKPACK_3")
		Set("아기 너구리 모양 인형 배낭.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BACKPACK_4")
		Set("동심 어린 옷차림에 어울리는 병아리 배낭.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BACKPACK_5")
		Set("솜구름 같은 곱슬털이 굽은 뿔을 덮고 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BACKPACK_6")
		Set("버터나 잼부터 좀 발라야겠다. 안 그러면 씹히지도 않는다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BAGUETTE")
		Set("이제 훨씬 부드러워졌다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BAGUETTE_EDIBLE")
		Set("우리 저금이 들어 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BANKATM")
		Set("성채 중심의 표식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BANNER")
		Set("소풍 갈 때 빠질 수 없는 수제 바구니.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BASKET")
		Set("복잡한 아름다움을 지닌 백자 욕조.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BATHTUB")
		Set("오래가고 안전하며 친환경적이다. 손전등에 든든한 전력을 공급한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BATTERY1")
		Set("일광욕을 즐긴다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BEACHCHAIR")
		Set("해변과 여름!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BEACH_UMBRELLA")
		Set("둘이 나눠 앉기에 넉넉한 자리.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BENCH")
		Set("그림자가 내 손끝을 타고 흐른다!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BLACKPEN")
		Set("윈저 왕조 시대의 가구 미학. 선이 우아하고 장중하며 고전적인 질감과 수납을 겸한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_BOOKCASE")
		Set("외짝 유리문의 크림빛 빈티지 조각 진열장.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CABINET")
		Set("짭조름한 바다 소금 맛.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAN0")
		Set("자, 밥 먹자!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAN1")
		Set("맛있는 생선포!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAN2")
		Set("간에 기별도 안 간다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAN3")
		Set("이제 그렇게 무섭진 않아 보인다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAN4")
		Set("맛있는 잔멸치!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAN5")
		Set("황동과 주철로 만든 깡통 공방. 증기와 톱니의 굉음 속에서 온갖 통조림을 찍어 낸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CANNER")
		Set("둥글둥글한 빈티지 소형 승용차.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAR")
		Set("안전벨트 매. 이제 출발할 준비가 됐다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAR_KEY")
		Set("금빛으로 반짝반짝, 참 예쁘다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CATCOIN")
		Set("해먹과 발판, 스크래처를 갖췄다. 고양이에게 쉼터이자 놀이터가 된다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CAT_TREE")
		Set("고성의 귀중한 물자를 두려고 지었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CELLAR")
		Set("음색이 낮고 아득해, 고성 깊은 곳의 우수 어린 선율을 울린다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CELLO")
		Set("피렌체의 예술적 멋이 담긴 가죽 스툴.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHAIR_1")
		Set("멋스러운 원목 의자.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHAIR_2")
		Set("흔들의자에 앉아 나른한 오후를 즐기고 싶다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHAIR_3")
		Set("연한 흰 몸체에 금박 테두리. 무척 고전적인 여닫이 구조.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHAIR_4")
		Set("화려한 둥근 스툴.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHAIR_5")
		Set("주점 프런트와 어울리는 하이 스툴.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHAIR_6")
		Set("주철로 만든 빈티지 단야로. 맹렬한 불길로 장작을 벼려 낸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHARCOAL_STOVE")
		Set("뚜껑에 새겨진 단풍잎 잎맥에 지난가을 숲의 한숨이 아직 봉해져 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHEST")
		Set("돌과 나무, 붉은 기와로 지은 눈뼈 문장 개집. 충직한 동무에게 따뜻한 쉼터를 준다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHESTER_HOUSE")
		Set("진귀한 에메랄드를 박은 화려한 보물상자. 왕실의 보물과 비경의 희귀품을 잠가 둔다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHEST_2")
		Set("유럽풍 백자 화분에 금박 장식. 금테 접란과 흰 꽃을 심은\n빈티지하고 단아한 실내 꽃꽂이 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CHLOROPHYTUM_COMOSUM_POTTED")
		Set("엮은 바구니에 연보랏빛 콜키쿰이 담겼다. 리본으로 꾸민 낭만적인 가을 풍물.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_COLCHICUM")
		Set("붉은 빈티지 전기 냄비. 구리솥과 화구 사이로 김이 감돈다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_COOKPOT")
		Set("오크색 전기 압력솥. 가정 주방에서 두루 쓰는 다기능 조리기구.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_COOKPOT_2")
		Set("충성을 뜻하는 십자 한손검.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_CROSS_SWORD")
		Set("온갖 장비를 분해해 재료를 되찾아 준다. 다만 시간이 걸린다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_DISASSEMBLER")
		Set("돌 틈에서 짭짤한 바닷바람 냄새가 난다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_DOCK_KIT")
		Set("블랙골드 배색 신사 예복 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_DRESS_FORM_M")
		Set("검은 드레스에 흰 테두리, 리본 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_DRESS_FORM_W")
		Set("정신이 번쩍 든다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_DRINK_COFFEE")
		Set("맛있는 탄산음료!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_DRINK_COLA")
		Set("정신을 차리는 데 도움이 되는 차.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_DRINK_TEA")
		Set("공들여 만든 오크 이젤.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_EASEL")
		Set("고전적인 다이얼과 접이식 날개로 만든 피서 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FAN")
		Set("묶어 둔 게 좀 허술해 보인다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FARM_TOOLS_CONTAINER")
		Set("반듯반듯한 석조 난간. 무척 튼튼해 보인다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FENCE")
		Set("쌍기둥 장식 울타리. 분홍 꽃과 푸른 덩굴이 감겨 꽃다발 기둥과 잘 어울린다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FENCE_2")
		Set("마그네슘 석회암으로 쌓은 중세 성벽 칸막이.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FENCE_3")
		Set("묵직한 질감의 문짝.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FENCE_GATE")
		Set("앞치마를 두른 히든 메이드 피규어.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_1")
		Set("동화 속 이야기.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_2")
		Set("모험길의 한 장면.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_3")
		Set("다정한 의사의 상.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_4")
		Set("굳센 전사의 상.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_5")
		Set("시골의 정취가 물씬 난다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_6")
		Set("야구를 사랑하는 윌슨.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_7")
		Set("완전 무장한 병사 인형.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIGURINE_8")
		Set("거리의 소방 시설.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FIREPLUG")
		Set("잡은 물고기를 잠시 담아 두는 바구니.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FISH_BASKET")
		Set("붉은 오크 장식장의 조각 물결무늬 안에 17세기 상선 잔해의 짠내가 잠겨 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FISH_TANK")
		Set("짙은 보랏빛 책장에 작은 수생 생태계가 한 칸 들어 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FISH_TANK_2")
		Set("산뜻한 초록 몸체. 늘 들고 다니기 좋고 튼튼한 손전등.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FLASHLIGHT")
		Set("느긋하고 산뜻한 전원의 분위기를 자아낸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FLOWERCART")
		Set("언제 어디서나 갓 만든 별미를 즐긴다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FOOD_TRUCK")
		Set("쫓아가기 벅차다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FOOTBALL")
		Set("J 키로 패스, K 키로 슛.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FOOTBALL_WITHOWNER")
		Set("야외 석조 예술.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FOUNTAIN")
		Set("개구리 모양 방수 세트.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FROG_RAINCOAT")
		Set("여행하는 모험가들이 자주 들르는 프런트.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FRONTDESK")
		Set("초록빛 빈티지 원형 석유 무쇠 난로.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_FURNACE")
		Set("안에 뭐가 들어 있을까..", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_GACHA")
		Set("저 손잡이를 돌리려면 동전이 좀 필요할 것 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_GACHA_MACHINE")
		Set("95 휘발유는 옥탄가가 높고 노킹에 강하다. 고압축 차량에 맞고 황이 적어 깨끗하며 출력이 안정적이다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_GASOLINE")
		Set("주방의 에너지원.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_GAS_CANISTER")
		Set("예전엔 여기에 카나리아를 길렀는데, 지금은 글로머의 보금자리가 되었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_GLOMMER_HOUSE")
		Set("준비됐다!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_GOAL")
		Set("사무실의 \"공기 정화사\". 도시 사람의 숨결을 누구보다 잘 안다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_GREEN_PALM")
		Set("빈티지 원목 손수레. 옛 시절의 나무 운반구다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HANDCART")
		Set("짧은 거리 운반 도구.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HANDCART_2")
		Set("보헤미안 민속 무늬의 술 장식 해먹. 발코니와 정원의 느긋한 그네.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HANGING_BED")
		Set("보석으로 장식한 침상.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HANGING_BED_2")
		Set("소리가 맑고 투명해, 중세 선경 같은 몽환적인 악장을 빚어낸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HARP")
		Set("대주방장의 모자.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_COOKER")
		Set("단출한 챙 넓은 낚시 모자.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_FISHERMAN")
		Set("우아한 챙 넓은 예모.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_HEPBURN")
		Set("바닥에 난 구멍은 이미 때웠다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_IRON_PAN")
		Set("꼭 왕실 의식 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_KINGCROWN")
		Set("평범한 기사가 쓰는 투구.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_KNIGHT")
		Set("이국적인 멋의 챙 넓은 밀짚모자.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_MEXICO")
		Set("이게 쓸모 있어질 것 같은 예감이 든다!", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_MOTORCYCLE")
		Set("무척 맛있어 보인다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_NOODLES")
		Set("뿔과 귀덮개 털이 달린 점박이 사슴무늬 모자.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_REINDEER")
		Set("북유럽 용 잡는 영웅의 투구.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_SIGURD")
		Set("시골풍 해바라기 밀짚모자.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_SUNFLOWER")
		Set("백장미 머리 장식이 달려 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAT_WHITE_ROSE")
		Set("금빛 건초를 가득 싣고, 시골의 고요함이 번진다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HAY_CART")
		Set("북유럽의 용 잡는 성검 그람.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HOLY_SWORD")
		Set("호박빛 단내가 흐른다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_HONEY_BOX")
		Set("세월이 느껴지는 파란 냉장고.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ICEBOX")
		Set("무척 귀여운 잠자는 곰 소형 냉장고. 소녀들에게 인기가 많다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ICEBOX_2")
		Set("음식을 오래도록 신선하게 보관한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ICEBOX_3")
		Set("주황과 흰색 배색의 식품 냉장고.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ICEBOX_BIG")
		Set("이 정밀한 기계로 얼음을 만들 수 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ICEMAKER")
		Set("자잘한 일상을 적어 둔다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_JOURNAL")
		Set("비계와 살코기가 어우러진 꼬치에 향신료가 듬뿍 묻었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_KEBAB")
		Set("금박 덩굴이 따뜻한 빛에 어리고, 프랑스 궁정의 우아함이 흐른다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LAMP")
		Set("세 갈래로 뻗은 금박 조각 촛대.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LAMP_2")
		Set("불을 밝히는 촛대.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LAMP_3")
		Set("이미 다 타 버렸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LAMP_3_NOFUEL")
		Set("불빛이 참 곱다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LANTERN")
		Set("희미한 빛이 밤하늘의 별 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LANTERN_2")
		Set("희미한 빛이 은은하게, 신비롭고 기묘한 기운을 띤다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LANTERN_3")
		Set("공방에서 흔히 쓰는 가죽 보관함.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LEATHER_STORAGE_CHEST")
		Set("전원풍 축사.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_LIVESTOCKBARN")
		Set("정교한 저택 문패에 철제 우편함이 달려 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_MAILBOX")
		Set("완다 여사가 가장 아꼈다는 탁상시계. 이미 멈춰 버렸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_MANTEL_CLOCK")
		Set("이게 내 전 재산이다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_MONEYBOX")
		Set("주철 조각 기둥에 유리 갓이 따뜻한 빛을 퍼뜨려 궁성 담장의 얼룩진 그림자를 비춘다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_MUSHROOM_LIGHT")
		Set("장미빛 원목 조명. 장인의 손길이 닿은 질감과 부드러운 빛이 집안의 단아한 순간을 붙든다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_MUSHROOM_LIGHT_2")
		Set("주점 앞 가로등.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_MUSHROOM_LIGHT_3")
		Set("안에 아직 불붙기 쉬운 게 조금 남은 것 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_OIL_BARREL")
		Set("빈티지하고 정교한 오븐. 좋아하는 재료를 굽는 데 쓴다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_OVEN")
		Set("귀여운 테디베어 도시락 가방. 여행길 끼니를 챙겨 주는 동무.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PACK")
		Set("빅토리아풍 메이드가 눈 감고 쉬는 치즈냥이를 안고 있는 유화.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PAINTING_MAID")
		Set("그림 속 시 부인은 어쩐지 조금 지쳐 보인다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PAINTING_XI")
		Set("녹슨 프라이팬은 이제 요리에 못 쓴다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PAN")
		Set("좀 천천히 몰면 나으려나.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PARTS_CAMERA_1")
		Set("그래도 조금 어지럽다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PARTS_CAMERA_2")
		Set("더 나다운 무언가를 찾아서.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PARTS_COLOUR")
		Set("황야에서 이런 기계를 만들어 내다니 보통 일이 아니다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PARTS_ENGINE")
		Set("밤에 또 볼 수 있을까?", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PARTS_LIGHT")
		Set("차 안 음악에 신경 쓰는 사람이 꽤 많은 것 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PARTS_MUSIC")
		Set("쥐고 있으면 손바닥에 마력이 흐르는 것 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PARTS_WHEEL")
		Set("빈티지 향수백합 화분. 집 안을 산뜻하게 꾸미는 초록 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PERFUME_POTTED")
		Set("다이얼이 돌아가는 딸깍 소리가 텅 빈 수화기 속에서 어느 세기의 통화 중 신호를 되풀이한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PHONOGRAPH")
		Set("단아한 홀 연주용 피아노.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PIANO")
		Set("밀봉해 신선하게 지키는 오크 통. 재료를 절이는 데 쓴다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PICKLING_BARREL")
		Set("저 인형 참 귀엽다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PLUSHIE_NIGHTSTAND")
		Set("버니... 너니?", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PLUSHIE_NIGHTSTAND_WILLOW")
		Set("몸과 마음을 달랜다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POND")
		Set("소나무 개척단원들이 가장 좋아하는 텐트. 야외 캠핑에 제격이다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PORTABLETENT")
		Set("야외 탐험과 야영에서 든든하고 믿음직한 냄비.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PORTABLE_COOK_POT")
		Set("너구리 꼬리 모양 손잡이가 달린 도기 숯불 뚝배기.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PORTABLE_COOK_POT_2")
		Set("열대우림의 정취를 담은 브라질나무 화분. 집에 초록을 더한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED")
		Set("콜롬비아 열대우림이 원산지인 안스리움 장식 화분.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_ANTHURIUM")
		Set("정성껏 다듬은 베리 화분.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_BERRY")
		Set("작고 고운 꽃이 초록 구체와 선명한 대비를 이루는 귀여운 화분.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_CACTUS")
		Set("작고 정갈한 벚꽃 사랑초 화분. 연분홍 벚꽃빛 작은 꽃이 핀다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_CHERRY")
		Set("작게 기른 야자수 화분.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_COCONUT")
		Set("치자꽃은 순결과 아름다움, 영원한 사랑을 뜻한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_GARDENIA")
		Set("이국적인 도기 화분에 심은 여러 팔 선인장. 야성적인 멕시코의 정취를 집으로 들인다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_MEXICO")
		Set("앵초는 무척 낭만적인 꽃이다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_MONETPRIMROSE")
		Set("잎 모양이 독특하고 사철 푸르며 줄기 마디가 굵다. 실내 대형 관엽식물의 명품이다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_MONSTERA")
		Set("수선화는 흔한 관상식물이지만 꽃을 아끼는 이들에게 두루 사랑받는다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_NARCISSUS")
		Set("백장미의 순결과 백합의 우아함. 순수한 사랑을 뜻한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_ROSE")
		Set("연회장에 흔히 놓는 진열용 화분.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_ROSE2")
		Set("잎이 곧고 반듯하며 무늬가 독특하다. 단정함과 야생의 멋을 함께 지녔다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_SNAKEPLANT")
		Set("햇살을 가득 담은 대바구니 해바라기. 체스터도 다가와 냄새를 맡고 싶어 한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_POTTED_SUNFLOWER")
		Set("그늘에 강하고 공기를 맑게 하는 실내 초록 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_PRINCESS_POTTED")
		Set("큰 저택에 어울리는 가죽 소파.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_REDLONGSOFA")
		Set("방을 잘 꾸며 주어 실내를 한결 예쁘게 만든다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RED_ROSE_POTTED")
		Set("밀 수 있을 것 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ROADBLOCK")
		Set("건축용 석재를 가지런히 넣어 둔다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ROCK_BIN")
		Set("유럽풍 굽 높은 화병. 백자 몸체에 금박 장식을 얹고\n붉은 장미를 꽂은 빈티지 화려한 꽃꽂이 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_ROSE_BIG_POTTED")
		Set("프랑스 오뷔송 실크 태피스트리. 무늬가 정교하고 빛깔이 화려하다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_AUBUSSON")
		Set("메이드장이 우리 같은 하급 메이드들에게 카펫을 거두라며 남긴 가죽 원통 가방.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_BAG")
		Set("거실을 꾸미는 체크 카펫.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_CASTLEBLUEWHITE")
		Set("밟으면 그 감촉이 참 마음을 놓이게 한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_DOORMAT")
		Set("자연의 산뜻함과 고요함을 집 안으로 들인다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_FOREST")
		Set("비엔나의 단아함에 벨벳의 촉감을 더한 타원 카펫.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_OVAL")
		Set("무늬가 정교하고 촉감이 부드러운 단아한 정원형 카펫. 편안하고 포근하다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_PLATONI")
		Set("유럽 고전 기법에서 비롯된 직물.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_SAVANNAH")
		Set("중세 장인이 손으로 짠 카펫.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_SOPHIA")
		Set("전통 평직 격자. 질기고 평평해 빈티지 인테리어에 제격이다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_TRADITION")
		Set("인디언 부족 토템을 녹여 냈다. 기하 무늬와 민족적 색채가 부딪혀 독특한 멋을 낸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_TRIANGLE")
		Set("등나무로 엮은 전원풍 카펫.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_RUG_WOVEN")
		Set("궁정 무도회와 밤의 주점에 낭만을 더한다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SAXOPHONE")
		Set("해바라기 모자를 쓴 허수아비.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SCARECROW")
		Set("불과 도둑을 막는 회색 강철 금고.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SECURITY_SAFE")
		Set("황금빛 은행나무를 한 그루 키울 수 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SEED_GINKGO")
		Set("열대 파초나무를 한 그루 키울 수 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SEED_PLANTAIN")
		Set("금박 선을 두른 무광 검정 재봉틀. 시간의 자국이 남은 소장품.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SEWINGMACHINE")
		Set("십자 문장을 새겼다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SHIELD")
		Set("두드리고 담금질해 장비를 고친다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SMITHY")
		Set("고급스러운 불로뉴 레이스 가죽 소파.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SOFA_1")
		Set("정교한 조각에 장미빛을 더했다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_SOFA_3")
		Set("길거리 시장에서 흔히 보는 진열대.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_STALL")
		Set("노란 꽃으로 꾸민 전원풍 등바구니. 손으로 엮은 가정용 수납함.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_STORAGE_BASKET")
		Set("불로뉴 레이스 식탁.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE")
		Set("붉고 정교한 긴 식탁.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_10")
		Set("얼른 한판 치고 싶은데, 이거 되는 건가?", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_11")
		Set("아치형 칸마다 좋은 술과 술통을 진열해 두었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_12")
		Set("푸른 유리 상판에 소용돌이 덩굴무늬를 더했다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_13")
		Set("소음 없는 후드를 갖춘 조리대.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_14")
		Set("포근한 욕실 분위기.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_15")
		Set("예장 기둥과 짝을 이루는 아치문.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_16")
		Set("이탈리아 예술의 도시에서 온, 낭만적인 이야기가 담긴 가구.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_2")
		Set("멋스러운 나무 탁자 위에 격자 식탁보를 덮었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_3")
		Set("원목 조각 장미빛 식탁. 단아하고 기품 있는 식사 자리의 으뜸.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_4")
		Set("금박 조각이 거울빛에 어리고, 고전적인 벨벳이 화장대의 품격을 받쳐 준다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_5")
		Set("유럽풍 빈티지 조각 전시대. 크리스마스풍 식탁보를 덮었다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_6")
		Set("유럽풍 기둥식 세면대. 금박 장식 무늬와 거울장을 갖춘 빈티지하고 화려한 모양새.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_7")
		Set("소용돌이 기둥 장식과 아치형 벽감, 상판에는 화병과 책. 빈티지 장식용 벽난로 구성물.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_8")
		Set("원목 개수대장.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TABLE_9")
		Set("시간을 실어 나르는 소리의 결.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TAPEPLAYER")
		Set("누렇게 바랜 낡은 녹음 테이프.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TAPE_1")
		Set("화려한 연회에 어울린다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TAPE_2")
		Set("풀과 나무, 산들바람의 산뜻함이 가득하다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TAPE_3")
		Set("격자 유리창이 참 반짝거린다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TELEPHONE_BOOTH")
		Set("주홍빛 침대 휘장의 그늘 속에 빅토리아 시대의 성대한 꿈이 웅크리고 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TENT")
		Set("둥글둥글한 토스터 모양.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TOASTER")
		Set("변기는 물론 카펫까지 빨아들일 수 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TOILET_SUCTION")
		Set("청결은 중요하다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TRASH_CAN")
		Set("황금빛 낙엽이 천천히 흩날린다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TREE_GINKGO")
		Set("넓은 잎을 펼친 파초나무.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TREE_PLANTAIN")
		Set("맛있는 디저트.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TRUCK_FOOD_1")
		Set("두툼하고 육즙 가득한 닭다리 버거.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TRUCK_FOOD_2")
		Set("진한 바비큐 풍미.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TRUCK_FOOD_3")
		Set("튀긴 간식.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TRUCK_FOOD_4")
		Set("코코넛 향 찬 음료. 갈증을 풀고 더위를 식힌다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TRUCK_FOOD_5")
		Set("게임기를 얹은 빈티지 텔레비전. 전원을 누르면 픽셀이 현실로 빚어진다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_TV")
		Set("같이 로리타 드레스 입고 나갈래?", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_UMBRELLA")
		Set("온갖 광고가 붙어 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_UTILITY_POLE")
		Set("좀 녹슨 것 같다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_VENDING_MACHINE")
		Set("신고전주의 호두나무 옷장.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WARDROBE")
		Set("이것에 얽힌 이야기가 몹시 궁금하다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WAR_HOE")
		Set("금속 테두리를 두른 정교한 세탁기.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WASHER")
		Set("알라딘은 이미 깊은 잠에 빠져 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WATERINGCAN")
		Set("양식에 흔히 쓰는 포크. 나이프와 함께 쓴다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_1")
		Set("무척 잘 드는 식사용 나이프.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_2")
		Set("이건... 제법 묵직한 구리 숟가락인데.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_3")
		Set("샤를리 부인이 가장 좋아했다는 와인이란다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_4")
		Set("구리 손잡이 뒤집개에 반짝이는 보석이 박혀 있다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_5")
		Set("열이 잘 전해지지 않아 데지 않는다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_6")
		Set("채소를 썰고 뼈를 자른다. 요리사의 필수품.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_7")
		Set("원목 밀대.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_8")
		Set("제과용 거품기.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WEAPON_9")
		Set("실용과 예술을 겸한 정교한 무늬의 고전 돌우물.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WELL")
		Set("징시 가구를 기록한 책. 포근하고 단아한 보금자리를 만드는 데 도움이 된다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WIKI_BOOK")
		Set("킨더다이크 마을의 풍차 공예품.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WINDMILL")
		Set("벽난로 장작을 가지런히 넣어 둔다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_WOOD_BIN")
		Set("햇볕이 배 위로 쏟아지고, 버터 한 덩이가 바닥에 퍼진다.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_XUNCAT")
		Set("순금으로 만든 정교한 트로피.", "CHARACTERS", "GENERIC", "DESCRIBE", "JX_XUNCAT_SUPERBIGCUP")
		Set("빈티지한 흑백 배색 타일. 욕실에 깔면 좋겠다.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_BATH")
		Set("거실과 침실을 단아하게 꾸미는 장식 카펫.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_CORRIDOR")
		Set("화강암을 닮은 알갱이 질감. 격자무늬 빈티지 카펫이 고급스러움을 드러낸다.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_GRANITE")
		Set("야외 정원과 테라스, 보도, 화단을 위해 만든 사각 포장재.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_JX_COURTYARD")
		Set("정원에 깔기에 좋다.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_JX_COURTYARD2")
		Set("거리 바닥을 꾸미기에 좋은 마름모 타일.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_JX_GREENDIAMOND")
		Set("홀 바닥 타일.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_JX_MANSION")
		Set("따뜻한 색조의 실내 바닥 타일.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_JX_WHITESQUARE")
		Set("궁정의 멋이 밴 원목 복합 마루.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_JX_WOOD")
		Set("천연 티크의 결이 부드럽고 곱다.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_JX_WOOD2")
		Set("기하 사각과 마름모 무늬에 대비색 테두리를 둘렀다. 고전적인 장식 직물.", "CHARACTERS", "GENERIC", "DESCRIBE", "TURF_REDDISH_BROWN")
		Set("유럽풍 빈티지 석조 담기둥. 꼭대기에 둥근 돌무늬 고리 장식이 있고\n벽돌 몸체에 조각 받침을 더한 고전적인 장식 건축물.", "CHARACTERS", "GENERIC", "DESCRIBE", "WALL_JX_STONE")
		Set("이오니아식 소용돌이 기둥머리에 꽃과 덩굴을 둘러 고전적인 낭만이 흐른다.", "CHARACTERS", "GENERIC", "DESCRIBE", "WALL_JX_STONE_2")
		Set("유럽 고성의 뾰족지붕 고딕 담장. 토템 조각을 새긴 어두운 분위기의 정원 장식.", "CHARACTERS", "GENERIC", "DESCRIBE", "WALL_JX_STONE_3")
		Set("마그네슘 석회암으로 쌓은 중세 성벽. 흙 둔덕 위에 세운 것이 남다르다.", "CHARACTERS", "GENERIC", "DESCRIBE", "WALL_JX_STONE_4")
		Set("중세에 흔하던 조경 담장. 주로 성의 정원에 쓰였다.", "CHARACTERS", "GENERIC", "DESCRIBE", "WALL_JX_STONE_5")
		Set("유럽풍 저택의 상록 생울타리. 별장 조경용 장식 식물.", "CHARACTERS", "GENERIC", "DESCRIBE", "WALL_JX_STRAW_1")
		Set("향이 아주 좋은 나무 기둥.", "CHARACTERS", "GENERIC", "DESCRIBE", "WALL_JX_WOOD_1")
		Set("이 차 엔진이 좀 녹슨 것 같다...\n누군가 고치는 중이다...", "JX_CAR_CANNOT_TAKE_IT")
		Set("시원하고 맛있다! 한 잔 더!", "JX_DRINKS_BUFF_ONATTACHED")
		Set("여운이 길게 남는다...", "JX_DRINKS_BUFF_ONDETACHED")
		Set("안에 전지가 없다..", "JX_FLASHLIGHT_NOBATTERY")
		Set("그만한 돈이 없다.", "JX_FOOD_TRUCK_HAVENOTENOUGHCOINS")
		Set("용 잡는 비술", "JX_HOLY_SWORD_TEXT")
		Set("기록 ", "JX_JOURNAL", "ANNOUNCE_1")
		Set("날짜 : ", "JX_JOURNAL", "DATE_1")
		Set("일째", "JX_JOURNAL", "DATE_2")
		Set("삭제", "JX_JOURNAL", "DELETE_1")
		Set("삭제 확인", "JX_JOURNAL", "DELETE_2")
		Set("전부 삭제", "JX_JOURNAL", "DELETE_3")
		Set("숫자를 입력하세요", "JX_JOURNAL", "NEED_NUM")
		Set("내용 없음", "JX_JOURNAL", "NO_CONTENT")
		Set("이전 쪽", "JX_JOURNAL", "TURN_PAGE_LEFT")
		Set("다음 쪽", "JX_JOURNAL", "TURN_PAGE_RIGHT")
		Set("통조림 만들기", "JX_MAKE_CAN")
		Set("숯 굽기", "JX_MAKE_CHARCOAL")
		Set("얼음 만들기", "JX_MAKE_ICE")
		Set("공개 음향", "JX_PIANO_CHAT")
		Set("의자를 하나 찾아서 앉아 연주하자.", "JX_PIANO_FINDCHAIR")
		Set("후지산 아래", "JX_PIANO_MUSIC", "NAME")
		Set("환희의 송가", "JX_PIANO_MUSIC2", "NAME")
		Set("비공개 음향", "JX_PIANO_MUTE")
		Set("Cover by PAUL LIU  사용 허가됨", "JX_PIANO_PANEL_2_TEXT")
		Set("의 금고", "JX_SECURITY_SAFE", "SET_OWNERNAME")
		Set("비밀번호를 설정했다. 번호는 : ", "JX_SECURITY_SAFE", "SET_PASSWORD_1")
		Set(" 그리고 ", "JX_SECURITY_SAFE", "SET_PASSWORD_2")
		Set("비밀번호가 틀렸다.", "JX_SECURITY_SAFE", "UNLOCK_FAIL")
		Set("백설공주가 이 세상에서 가장 아름다운 여인입니다.", "JX_TABLE_5_ANSWER")
		Set("거울아 거울아, 이 세상에서 가장 아름다운 여인은 누구니?", "JX_TABLE_5_QUESTION")
		Set("물건을 내렸다가 다시 올리면 위치를 바로잡을 수 있다.", "JX_TABLE_6_OFFSET")
		Set("다 떨어졌다. 다음에 다시 와 보자.", "JX_VENDING_MACHINE_NO_DRINKS")
		Set("공격력 +5% 효과가 나왔다", "JX_WASHER_BUFFS", "COMBAT_DAMAGE_MODIFIER")
		Set("피해 감소 +5% 효과가 나왔다", "JX_WASHER_BUFFS", "COMBAT_TAKEN_MODIFIER")
		Set("정신력 회복 \"+16/일\" 효과가 나왔다", "JX_WASHER_BUFFS", "DAPPERNESS")
		Set("체력 회복 \"+16/일\" 효과가 나왔다", "JX_WASHER_BUFFS", "HEALTH_REGEN")
		Set("허기 속도 -5% 효과가 나왔다", "JX_WASHER_BUFFS", "HUNGER_MODIFIER")
		Set("보온/단열 +30 효과가 나왔다", "JX_WASHER_BUFFS", "INSULATOR")
		Set("조명 효과가 나왔다", "JX_WASHER_BUFFS", "LIGHT_RADIU")
		Set("이동속도 +5% 효과가 나왔다. 운이 좋군!", "JX_WASHER_BUFFS", "WALKSPEEDMULT")
		Set("방수 +10% 효과가 나왔다", "JX_WASHER_BUFFS", "WATERPROOFER")
		Set("뭐 하는 거야", "JX_WHAT_ARE_YOU_DOING")
		Set("자동 선택", "JX_WIKI", "AUTOCHOOSE")
		Set("배경음악 : 꺼짐", "JX_WIKI", "BGM_OFF")
		Set("배경음악 : 켜짐", "JX_WIKI", "BGM_ON")
		Set("총 문항 수 : ", "JX_WIKI", "CURRENT_CORRECT_TEXT_1")
		Set("맞힌 문항 수 : ", "JX_WIKI", "CURRENT_CORRECT_TEXT_2")
		Set("정답률 : ", "JX_WIKI", "CURRENT_CORRECT_TEXT_3")
		Set("모드 위키", "JX_WIKI", "MODWIKI")
		Set("브라질나무 화분", "JX_WIKI", "NAME")
		Set("다음 문제", "JX_WIKI", "NEXTQUESTION")
		Set("jx_potted", "JX_WIKI", "PREFABNAME")
		Set("꽃이 달린 화분은 보통 어떤 효과를 가질까요 :", "JX_WIKI", "QUESTION")
		Set("초기화", "JX_WIKI", "RESET_STATISTICS")
		Set("물건 검색...", "JX_WIKI", "SEARCH")
		Set("정답률 집계 시작", "JX_WIKI", "START_STATISTICS")
		Set("집계 중지", "JX_WIKI", "STOP_STATISTICS")
		Set("맛보기 퀴즈", "JX_WIKI", "TEST")
		Set("업데이트 내용", "JX_WIKI", "UPDATE_CONTENT")
		Set("더 자세한 웹 위키 보기 (주소를 복사해 브라우저에서 여세요)", "JX_WIKI", "VISITWIKI")
		Set("\"고양이 조련사\"라는 이름의 치즈냥이가 낮잠을 자고 있다. 깨우지 말자.", "JX_XUNCAT_CHECK")
		Set("고급 요리만 이 탁자에 올릴 수 있다.", "MUST_BE_PREPAREDFOOD")
		Set("기사 갑옷", "NAMES", "ARMOR_JX_KNIGHT")
		Set("징시 조각상", "NAMES", "CHESSPIECES_JX")
		Set("메이드 징시 조각상", "NAMES", "CHESSPIECE_JX")
		Set("뮤즈 여신 조각상", "NAMES", "CHESSPIECE_JX2")
		Set("스탠드 에어컨", "NAMES", "JX_AIR_CONDITIONER")
		Set("스탠드 에어컨 (바람 새는 중)", "NAMES", "JX_AIR_CONDITIONER_OPENED")
		Set("로리타 피크닉 토끼 가방", "NAMES", "JX_BACKPACK")
		Set("보닛 늘어진귀 토끼 가방", "NAMES", "JX_BACKPACK_2")
		Set("카라멜 티파티 고양이 가방", "NAMES", "JX_BACKPACK_3")
		Set("아기 너구리 인형 가방", "NAMES", "JX_BACKPACK_4")
		Set("달걀프라이 병아리 가방", "NAMES", "JX_BACKPACK_5")
		Set("잠자는 양 인형 가방", "NAMES", "JX_BACKPACK_6")
		Set("바게트", "NAMES", "JX_BAGUETTE")
		Set("냥냥코인 현금인출기", "NAMES", "JX_BANKATM")
		Set("성채 깃발", "NAMES", "JX_BANNER")
		Set("수제 피크닉 바구니", "NAMES", "JX_BASKET")
		Set("바로크 백자 욕조", "NAMES", "JX_BATHTUB")
		Set("전용 건전지", "NAMES", "JX_BATTERY1")
		Set("야외 비치체어", "NAMES", "JX_BEACHCHAIR")
		Set("야외 파라솔", "NAMES", "JX_BEACH_UMBRELLA")
		Set("흰 나무 공원 벤치", "NAMES", "JX_BENCH")
		Set("합류", "NAMES", "JX_BLACKPEN")
		Set("윈저 고전 찬장", "NAMES", "JX_BOOKCASE")
		Set("로코코 조각 유리장", "NAMES", "JX_CABINET")
		Set("다시마 통조림", "NAMES", "JX_CAN0")
		Set("런천미트 통조림", "NAMES", "JX_CAN1")
		Set("생선포 통조림", "NAMES", "JX_CAN2")
		Set("햄 통조림", "NAMES", "JX_CAN3")
		Set("야생고기 통조림", "NAMES", "JX_CAN4")
		Set("잔멸치 통조림", "NAMES", "JX_CAN5")
		Set("언더우드 통조림 기계", "NAMES", "JX_CANNER")
		Set("빈티지 딱정벌레 자동차", "NAMES", "JX_CAR")
		Set("자동차 열쇠", "NAMES", "JX_CAR_KEY")
		Set("냥냥코인", "NAMES", "JX_CATCOIN")
		Set("오크 캣타워", "NAMES", "JX_CAT_TREE")
		Set("알렉산더 지하 저장고", "NAMES", "JX_CELLAR")
		Set("궁정 유현 첼로", "NAMES", "JX_CELLO")
		Set("피렌체 가죽 스툴", "NAMES", "JX_CHAIR_1")
		Set("프로방스 체크 의자", "NAMES", "JX_CHAIR_2")
		Set("장미 가죽 흔들의자", "NAMES", "JX_CHAIR_3")
		Set("백자 변기", "NAMES", "JX_CHAIR_4")
		Set("만찬용 둥근 스툴", "NAMES", "JX_CHAIR_5")
		Set("주점 하이 스툴", "NAMES", "JX_CHAIR_6")
		Set("무쇠 숯화로", "NAMES", "JX_CHARCOAL_STOVE")
		Set("단풍나무 상자", "NAMES", "JX_CHEST")
		Set("체스터 집", "NAMES", "JX_CHESTER_HOUSE")
		Set("에메랄드 보석함", "NAMES", "JX_CHEST_2")
		Set("유럽풍 금테 접란 화분", "NAMES", "JX_CHLOROPHYTUM_COMOSUM_POTTED")
		Set("등바구니 콜키쿰", "NAMES", "JX_COLCHICUM")
		Set("빈티지 전기 냄비", "NAMES", "JX_COOKPOT")
		Set("빈티지 오크 압력솥", "NAMES", "JX_COOKPOT_2")
		Set("기사 십자검", "NAMES", "JX_CROSS_SWORD")
		Set("우르노스의 해체기", "NAMES", "JX_DISASSEMBLER")
		Set("항만 청석 부두 세트", "NAMES", "JX_DOCK_KIT")
		Set("블랙골드 연미복 마네킹", "NAMES", "JX_DRESS_FORM_M")
		Set("고딕 로리타 마네킹", "NAMES", "JX_DRESS_FORM_W")
		Set("커피", "NAMES", "JX_DRINK_COFFEE")
		Set("시원한 콜라", "NAMES", "JX_DRINK_COLA")
		Set("우롱차", "NAMES", "JX_DRINK_TEA")
		Set("이젤", "NAMES", "JX_EASEL")
		Set("선풍기", "NAMES", "JX_FAN")
		Set("시골 농기구 걸이", "NAMES", "JX_FARM_TOOLS_CONTAINER")
		Set("고전 로마 기둥 난간", "NAMES", "JX_FENCE")
		Set("이오니아 쌍기둥 울타리", "NAMES", "JX_FENCE_2")
		Set("요크 성 칸막이", "NAMES", "JX_FENCE_3")
		Set("요크 성 대문", "NAMES", "JX_FENCE_GATE")
		Set("메이드 징시 피규어", "NAMES", "JX_FIGURINE_1")
		Set("빨간망토 웬디 피규어", "NAMES", "JX_FIGURINE_2")
		Set("조련사 웬디 피규어", "NAMES", "JX_FIGURINE_3")
		Set("간호사 웬디 피규어", "NAMES", "JX_FIGURINE_4")
		Set("기사 우디 피규어", "NAMES", "JX_FIGURINE_5")
		Set("웜우드의 휴일 피규어", "NAMES", "JX_FIGURINE_6")
		Set("야구선수 윌슨", "NAMES", "JX_FIGURINE_7")
		Set("전사 볼프강 피규어", "NAMES", "JX_FIGURINE_8")
		Set("옥외 소화전", "NAMES", "JX_FIREPLUG")
		Set("등나무 어롱", "NAMES", "JX_FISH_BASKET")
		Set("로코코 수조장", "NAMES", "JX_FISH_TANK")
		Set("비너스 어항", "NAMES", "JX_FISH_TANK_2")
		Set("밀러의 손전등", "NAMES", "JX_FLASHLIGHT")
		Set("편백 원예 꽃수레", "NAMES", "JX_FLOWERCART")
		Set("길거리 푸드트럭", "NAMES", "JX_FOOD_TRUCK")
		Set("축구공", "NAMES", "JX_FOOTBALL")
		Set("빌리안 저택 분수", "NAMES", "JX_FOUNTAIN")
		Set("개구리 우비", "NAMES", "JX_FROG_RAINCOAT")
		Set("주점 프런트", "NAMES", "JX_FRONTDESK")
		Set("노이부르크 석유난로", "NAMES", "JX_FURNACE")
		Set("뽑기 캡슐", "NAMES", "JX_GACHA")
		Set("뽑기 기계", "NAMES", "JX_GACHA_MACHINE")
		Set("95 무연 휘발유", "NAMES", "JX_GASOLINE")
		Set("가스통", "NAMES", "JX_GAS_CANISTER")
		Set("글로머의 나무집", "NAMES", "JX_GLOMMER_HOUSE")
		Set("축구 골대", "NAMES", "JX_GOAL")
		Set("페페로미아 화분", "NAMES", "JX_GREEN_PALM")
		Set("저택 손수레", "NAMES", "JX_HANDCART")
		Set("소형 목제 손수레", "NAMES", "JX_HANDCART_2")
		Set("보헤미안 엮음 해먹", "NAMES", "JX_HANGING_BED")
		Set("로렌 캐노피 침대", "NAMES", "JX_HANGING_BED_2")
		Set("귀족 고전 하프", "NAMES", "JX_HARP")
		Set("요리사 모자", "NAMES", "JX_HAT_COOKER")
		Set("버킷햇", "NAMES", "JX_HAT_FISHERMAN")
		Set("흑장미 체크 헵번 모자", "NAMES", "JX_HAT_HEPBURN")
		Set("무쇠솥 투구", "NAMES", "JX_HAT_IRON_PAN")
		Set("왕관", "NAMES", "JX_HAT_KINGCROWN")
		Set("기사 투구", "NAMES", "JX_HAT_KNIGHT")
		Set("솜브레로", "NAMES", "JX_HAT_MEXICO")
		Set("오토바이 헬멧", "NAMES", "JX_HAT_MOTORCYCLE")
		Set("달걀 라면 모자", "NAMES", "JX_HAT_NOODLES")
		Set("순록 니트 모자", "NAMES", "JX_HAT_REINDEER")
		Set("지크루드의 투구", "NAMES", "JX_HAT_SIGURD")
		Set("해바라기 밀짚모자", "NAMES", "JX_HAT_SUNFLOWER")
		Set("백장미 레이스 예모", "NAMES", "JX_HAT_WHITE_ROSE")
		Set("전원 건초 수레", "NAMES", "JX_HAY_CART")
		Set("지크루드의 성검", "NAMES", "JX_HOLY_SWORD")
		Set("저택 호박빛 벌통", "NAMES", "JX_HONEY_BOX")
		Set("빈티지 냉장고", "NAMES", "JX_ICEBOX")
		Set("잠자는 곰 소형 냉장고", "NAMES", "JX_ICEBOX_2")
		Set("플로라 냉장고", "NAMES", "JX_ICEBOX_3")
		Set("북극곰 냉동고", "NAMES", "JX_ICEBOX_BIG")
		Set("에우로파 제빙기", "NAMES", "JX_ICEMAKER")
		Set("일기장", "NAMES", "JX_JOURNAL")
		Set("조지아식 케밥", "NAMES", "JX_KEBAB")
		Set("빈티지 장식 침실등", "NAMES", "JX_LAMP")
		Set("조각 삼지 촛대", "NAMES", "JX_LAMP_2")
		Set("황동 촛잔", "NAMES", "JX_LAMP_3")
		Set("보석 장미 야간등", "NAMES", "JX_LANTERN")
		Set("고성 별빛 랜턴", "NAMES", "JX_LANTERN_2")
		Set("드라큘라 백작 랜턴", "NAMES", "JX_LANTERN_3")
		Set("가죽 수납함", "NAMES", "JX_LEATHER_STORAGE_CHEST")
		Set("시골 축사", "NAMES", "JX_LIVESTOCKBARN")
		Set("저택 문패 우편함", "NAMES", "JX_MAILBOX")
		Set("멈춰 버린 탁상시계", "NAMES", "JX_MANTEL_CLOCK")
		Set("지폐함", "NAMES", "JX_MONEYBOX")
		Set("고딕 궁정 가로등", "NAMES", "JX_MUSHROOM_LIGHT")
		Set("장미 원목 실내등", "NAMES", "JX_MUSHROOM_LIGHT_2")
		Set("주점 길잡이 등", "NAMES", "JX_MUSHROOM_LIGHT_3")
		Set("폐공업용 기름통", "NAMES", "JX_OIL_BARREL")
		Set("청동 테두리 오븐", "NAMES", "JX_OVEN")
		Set("로리타 곰돌이 도시락 가방", "NAMES", "JX_PACK")
		Set("메이드 징시와 고양이", "NAMES", "JX_PAINTING_MAID")
		Set("만찬이 끝난 뒤의 시 부인", "NAMES", "JX_PAINTING_XI")
		Set("주철 프라이팬", "NAMES", "JX_PAN")
		Set("블랙박스 α", "NAMES", "JX_PARTS_CAMERA_1")
		Set("블랙박스 β", "NAMES", "JX_PARTS_CAMERA_2")
		Set("스프레이 도료 캔", "NAMES", "JX_PARTS_COLOUR")
		Set("정밀 내연기관", "NAMES", "JX_PARTS_ENGINE")
		Set("야간 과속등", "NAMES", "JX_PARTS_LIGHT")
		Set("차량용 스피커", "NAMES", "JX_PARTS_MUSIC")
		Set("핸들 키트", "NAMES", "JX_PARTS_WHEEL")
		Set("향수백합 화분", "NAMES", "JX_PERFUME_POTTED")
		Set("고전 다이얼 전화기", "NAMES", "JX_PHONOGRAPH")
		Set("로열 베히슈타인 그랜드 피아노", "NAMES", "JX_PIANO")
		Set("오크 절임통", "NAMES", "JX_PICKLING_BARREL")
		Set("인형 협탁", "NAMES", "JX_PLUSHIE_NIGHTSTAND")
		Set("바스 로마 욕장", "NAMES", "JX_POND")
		Set("보헤미안 캠핑 텐트", "NAMES", "JX_PORTABLETENT")
		Set("캠핑용 냄비", "NAMES", "JX_PORTABLE_COOK_POT")
		Set("너구리 뚝배기", "NAMES", "JX_PORTABLE_COOK_POT_2")
		Set("브라질나무 화분", "NAMES", "JX_POTTED")
		Set("콜롬비아 안스리움 화분", "NAMES", "JX_POTTED_ANTHURIUM")
		Set("유럽풍 베리 화분", "NAMES", "JX_POTTED_BERRY")
		Set("클래식 선인장 화분", "NAMES", "JX_POTTED_CACTUS")
		Set("벚꽃 사랑초 화분", "NAMES", "JX_POTTED_CHERRY")
		Set("야자수 화분", "NAMES", "JX_POTTED_COCONUT")
		Set("치자꽃 화분", "NAMES", "JX_POTTED_GARDENIA")
		Set("멕시코 선인장 화분", "NAMES", "JX_POTTED_MEXICO")
		Set("모네 앵초 화분", "NAMES", "JX_POTTED_MONETPRIMROSE")
		Set("전통 몬스테라 화분", "NAMES", "JX_POTTED_MONSTERA")
		Set("웨일스 수선화 화분", "NAMES", "JX_POTTED_NARCISSUS")
		Set("순백의 꽃말 화분", "NAMES", "JX_POTTED_ROSE")
		Set("베로나의 만찬 화분", "NAMES", "JX_POTTED_ROSE2")
		Set("유럽풍 산세베리아 화분", "NAMES", "JX_POTTED_SNAKEPLANT")
		Set("대바구니 해바라기 화분", "NAMES", "JX_POTTED_SUNFLOWER")
		Set("그린프린세스 화분", "NAMES", "JX_PRINCESS_POTTED")
		Set("장미 조각 2인 소파", "NAMES", "JX_REDLONGSOFA")
		Set("샹그릴라 장미 화분", "NAMES", "JX_RED_ROSE_POTTED")
		Set("홍백 라바콘", "NAMES", "JX_ROADBLOCK")
		Set("저택 석재함", "NAMES", "JX_ROCK_BIN")
		Set("캐롤라 장미 백자 화분", "NAMES", "JX_ROSE_BIG_POTTED")
		Set("오뷔송 실크 태피스트리", "NAMES", "JX_RUG_AUBUSSON")
		Set("메이드의 레이스 카펫 가방", "NAMES", "JX_RUG_BAG")
		Set("남청백 체크 카펫", "NAMES", "JX_RUG_CASTLEBLUEWHITE")
		Set("데이지 세 송이 술 카펫", "NAMES", "JX_RUG_DOORMAT")
		Set("숲의 노래 사각 러그", "NAMES", "JX_RUG_FOREST")
		Set("비엔나 벨벳 타원 러그", "NAMES", "JX_RUG_OVAL")
		Set("플라토니 정원형 카펫", "NAMES", "JX_RUG_PLATONI")
		Set("사바나 수제 카펫", "NAMES", "JX_RUG_SAVANNAH")
		Set("소피아 수제 카펫", "NAMES", "JX_RUG_SOPHIA")
		Set("전통 평직 격자 카펫", "NAMES", "JX_RUG_TRADITION")
		Set("인디언 토템 삼각 러그", "NAMES", "JX_RUG_TRIANGLE")
		Set("전원 등나무 카펫", "NAMES", "JX_RUG_WOVEN")
		Set("빈티지 금관 색소폰", "NAMES", "JX_SAXOPHONE")
		Set("허수아비", "NAMES", "JX_SCARECROW")
		Set("금고", "NAMES", "JX_SECURITY_SAFE")
		Set("은행나무 씨앗", "NAMES", "JX_SEED_GINKGO")
		Set("파초 씨앗", "NAMES", "JX_SEED_PLANTAIN")
		Set("루비 빈티지 재봉틀", "NAMES", "JX_SEWINGMACHINE")
		Set("기사 붓꽃 방패", "NAMES", "JX_SHIELD")
		Set("대장간 화로", "NAMES", "JX_SMITHY")
		Set("불로뉴 레이스 가죽 소파", "NAMES", "JX_SOFA_1")
		Set("불로뉴 레이스 조합 소파", "NAMES", "JX_SOFA_2")
		Set("장미 조각 가죽 소파", "NAMES", "JX_SOFA_3")
		Set("보헤미안 좌판대", "NAMES", "JX_STALL")
		Set("전원 등나무 수납 바구니", "NAMES", "JX_STORAGE_BASKET")
		Set("불로뉴 레이스 식탁", "NAMES", "JX_TABLE")
		Set("만찬용 긴 식탁", "NAMES", "JX_TABLE_10")
		Set("당구대", "NAMES", "JX_TABLE_11")
		Set("금박 조각 와인장", "NAMES", "JX_TABLE_12")
		Set("카산드라 장식 테이블", "NAMES", "JX_TABLE_13")
		Set("주방 조리대", "NAMES", "JX_TABLE_14")
		Set("욕실 선반", "NAMES", "JX_TABLE_15")
		Set("장미목 무늬 아치문", "NAMES", "JX_TABLE_16")
		Set("피렌체 원목 식탁", "NAMES", "JX_TABLE_2")
		Set("프로방스 체크 사각 테이블", "NAMES", "JX_TABLE_3")
		Set("장미 조각 식탁", "NAMES", "JX_TABLE_4")
		Set("유럽풍 원목 화장대", "NAMES", "JX_TABLE_5")
		Set("고성 회랑 전시대", "NAMES", "JX_TABLE_6")
		Set("백자 기둥 세면대", "NAMES", "JX_TABLE_7")
		Set("소용돌이 기둥 석조 벽난로", "NAMES", "JX_TABLE_8")
		Set("주방 개수대", "NAMES", "JX_TABLE_9")
		Set("카세트 녹음기", "NAMES", "JX_TAPEPLAYER")
		Set("클래식 선율 테이프", "NAMES", "JX_TAPE_1")
		Set("연회장 무곡 테이프", "NAMES", "JX_TAPE_2")
		Set("유월의 숲 테이프", "NAMES", "JX_TAPE_3")
		Set("빨간 공중전화 부스", "NAMES", "JX_TELEPHONE_BOOTH")
		Set("바로크 돔형 침대", "NAMES", "JX_TENT")
		Set("토스터", "NAMES", "JX_TOASTER")
		Set("빨간 뚫어뻥", "NAMES", "JX_TOILET_SUCTION")
		Set("쓰레기통", "NAMES", "JX_TRASH_CAN")
		Set("황금잎 은행나무", "NAMES", "JX_TREE_GINKGO")
		Set("정원 파초나무", "NAMES", "JX_TREE_PLANTAIN")
		Set("프랑스식 파르페", "NAMES", "JX_TRUCK_FOOD_1")
		Set("햄버거", "NAMES", "JX_TRUCK_FOOD_2")
		Set("부리토", "NAMES", "JX_TRUCK_FOOD_3")
		Set("벨기에 감자튀김", "NAMES", "JX_TRUCK_FOOD_4")
		Set("태국 코코넛 워터", "NAMES", "JX_TRUCK_FOOD_5")
		Set("빈티지 텔레비전", "NAMES", "JX_TV")
		Set("고딕풍 고양이귀 양산", "NAMES", "JX_UMBRELLA")
		Set("거리 전신주", "NAMES", "JX_UTILITY_POLE")
		Set("음료 자판기", "NAMES", "JX_VENDING_MACHINE")
		Set("장미 조각 옷장", "NAMES", "JX_WARDROBE")
		Set("엔릴의 전투 괭이", "NAMES", "JX_WAR_HOE")
		Set("테두리 장식 세탁기", "NAMES", "JX_WASHER")
		Set("알라딘 램프 물뿌리개", "NAMES", "JX_WATERINGCAN")
		Set("빈 궁정풍 꽃차 주전자", "NAMES", "JX_WATERINGCAN_EMPTY")
		Set("루비 포크", "NAMES", "JX_WEAPON_1")
		Set("사파이어 나이프", "NAMES", "JX_WEAPON_2")
		Set("에메랄드 스푼", "NAMES", "JX_WEAPON_3")
		Set("샤를리 부인의 와인", "NAMES", "JX_WEAPON_4")
		Set("토파즈 뒤집개", "NAMES", "JX_WEAPON_5")
		Set("나무 주걱", "NAMES", "JX_WEAPON_6")
		Set("탄소강 식칼", "NAMES", "JX_WEAPON_7")
		Set("밀대", "NAMES", "JX_WEAPON_8")
		Set("자수정 거품기", "NAMES", "JX_WEAPON_9")
		Set("저택 문양 우물", "NAMES", "JX_WELL")
		Set("징시 가구 안내서", "NAMES", "JX_WIKI_BOOK")
		Set("네덜란드 작은 풍차", "NAMES", "JX_WINDMILL")
		Set("저택 장작함", "NAMES", "JX_WOOD_BIN")
		Set("낮잠 자는 고양이 조련사", "NAMES", "JX_XUNCAT")
		Set("냥냥 금 트로피", "NAMES", "JX_XUNCAT_SUPERBIGCUP")
		Set("빈티지 체크 욕실 타일", "NAMES", "TURF_BATH")
		Set("갈색 문양 회랑 카펫", "NAMES", "TURF_CORRIDOR")
		Set("화강암 무늬 쪽매 카펫", "NAMES", "TURF_GRANITE")
		Set("정원 보도 사각 타일", "NAMES", "TURF_JX_COURTYARD")
		Set("정원 잿빛 무늬 타일", "NAMES", "TURF_JX_COURTYARD2")
		Set("저택 녹색 마름모 타일", "NAMES", "TURF_JX_GREENDIAMOND")
		Set("저택 고리무늬 꽃 타일", "NAMES", "TURF_JX_MANSION")
		Set("따뜻한 갈적백 무늬 타일", "NAMES", "TURF_JX_WHITESQUARE")
		Set("궁정 원목 마루", "NAMES", "TURF_JX_WOOD")
		Set("주점 티크 마루", "NAMES", "TURF_JX_WOOD2")
		Set("빈티지 기하무늬 적갈 카펫", "NAMES", "TURF_REDDISH_BROWN")
		Set("고전 문장 장식 돌담", "NAMES", "WALL_JX_STONE")
		Set("이오니아 꽃다발 원기둥", "NAMES", "WALL_JX_STONE_2")
		Set("고성 고딕 돌담", "NAMES", "WALL_JX_STONE_3")
		Set("요크 성 돌담", "NAMES", "WALL_JX_STONE_4")
		Set("성곽 조경 담장", "NAMES", "WALL_JX_STONE_5")
		Set("저택 상록 생울타리", "NAMES", "WALL_JX_STRAW_1")
		Set("장미목 무늬 예장 기둥", "NAMES", "WALL_JX_WOOD_1")
		Set("냥냥코인을 받는다.", "NEED_CATCOIN")
		Set("도료를 더 낭비할 필요는 없다.", "NEED_NOT_COLOUR")
		Set("수리할 필요가 없다.", "NEED_NOT_REPAIR")
		Set("수선할 필요가 없다.", "NEED_NOT_SEWING")
		Set("이건 빨면 안 될 것 같은데..", "NEED_NOT_WASH")
		Set("기름을 넣어야겠다.", "NO_CAR_FUEL")
		Set("자동차 열쇠를 안 가져왔다.", "NO_CAR_KEY")
		Set("차에 아직 스피커가 없다.", "NO_MUSIC_PARTS")
		Set("조금 있다가 다시 오자", "OWN_WASHER_BUFF")
		Set("이쪽으로는 못 탄다.", "PASSENGERFAIL", "CANNOTSUCCESS")
		Set("자리가 다 찼다.", "PASSENGERFAIL", "ISFULL")
		Set("제법 묵직한 갑옷.", "RECIPE_DESC", "ARMOR_JX_KNIGHT")
		Set("메이드 징시 아가씨의 조각상을 만든다.", "RECIPE_DESC", "CHESSPIECES_JX")
		Set("징시 아가씨를 메이드 조각상으로 만든다.", "RECIPE_DESC", "CHESSPIECE_JX")
		Set("공원 장식 조각상.", "RECIPE_DESC", "CHESSPIECE_JX2")
		Set("시원한 바람을 내보낸다.", "RECIPE_DESC", "JX_AIR_CONDITIONER")
		Set("토끼 모양 배낭.", "RECIPE_DESC", "JX_BACKPACK")
		Set("토끼 모양 배낭.", "RECIPE_DESC", "JX_BACKPACK_2")
		Set("빈티지 삼색 고양이 배낭. 많이 담을 수 있다.", "RECIPE_DESC", "JX_BACKPACK_3")
		Set("음식을 신선하게 지켜 주는 배낭.", "RECIPE_DESC", "JX_BACKPACK_4")
		Set("삐약삐약 우는 배낭.", "RECIPE_DESC", "JX_BACKPACK_5")
		Set("곤히 자고 있는 양 배낭.", "RECIPE_DESC", "JX_BACKPACK_6")
		Set("전통적인 빵의 하나.", "RECIPE_DESC", "JX_BAGUETTE")
		Set("냥냥코인을 넣고 빼고 바꾼다.", "RECIPE_DESC", "JX_BANKATM")
		Set("누가 영주인지 알린다.", "RECIPE_DESC", "JX_BANNER")
		Set("음식을 담는 피크닉 바구니.", "RECIPE_DESC", "JX_BASKET")
		Set("몸을 담그고 마음을 가다듬자.", "RECIPE_DESC", "JX_BATHTUB")
		Set("구형 D형 건전지.", "RECIPE_DESC", "JX_BATTERY1")
		Set("해변 선베드.", "RECIPE_DESC", "JX_BEACHCHAIR")
		Set("해변 파라솔.", "RECIPE_DESC", "JX_BEACH_UMBRELLA")
		Set("흰 나무 2인 벤치.", "RECIPE_DESC", "JX_BENCH")
		Set("그림자 여왕이 내린 선물.", "RECIPE_DESC", "JX_BLACKPEN")
		Set("요리를 진열하는 창 없는 장.", "RECIPE_DESC", "JX_BOOKCASE")
		Set("모험가의 수집품을 진열한다.", "RECIPE_DESC", "JX_CABINET")
		Set("짭조름한 바다 소금 맛.", "RECIPE_DESC", "JX_CAN0")
		Set("자, 밥 먹자!", "RECIPE_DESC", "JX_CAN1")
		Set("맛있는 생선포!", "RECIPE_DESC", "JX_CAN2")
		Set("간에 기별도 안 간다.", "RECIPE_DESC", "JX_CAN3")
		Set("이제 그렇게 무섭진 않아 보인다.", "RECIPE_DESC", "JX_CAN4")
		Set("맛있는 잔멸치!", "RECIPE_DESC", "JX_CAN5")
		Set("밀봉식 식품 보존법.", "RECIPE_DESC", "JX_CANNER")
		Set("짐을 자동차 트렁크에 실을 수 있다.", "RECIPE_DESC", "JX_CAR")
		Set("새로운 장을 연다.", "RECIPE_DESC", "JX_CAR_KEY")
		Set("고양이의 포근한 시간.", "RECIPE_DESC", "JX_CAT_TREE")
		Set("귀중한 물자를 보관한다.", "RECIPE_DESC", "JX_CELLAR")
		Set("조각 장식 첼로.", "RECIPE_DESC", "JX_CELLO")
		Set("가죽 스툴에 앉아 잠깐 쉰다.", "RECIPE_DESC", "JX_CHAIR_1")
		Set("격자 천을 깐 원목 의자.", "RECIPE_DESC", "JX_CHAIR_2")
		Set("흔들의자에 앉아 나른한 오후를 즐긴다.", "RECIPE_DESC", "JX_CHAIR_3")
		Set("장식용 욕실 위생기구.", "RECIPE_DESC", "JX_CHAIR_4")
		Set("화려한 둥근 스툴.", "RECIPE_DESC", "JX_CHAIR_5")
		Set("질감이 살아 있는 하이 스툴.", "RECIPE_DESC", "JX_CHAIR_6")
		Set("나무를 구워 숯으로 만든다.", "RECIPE_DESC", "JX_CHARCOAL_STOVE")
		Set("고급스러운 유럽풍 나무 상자.", "RECIPE_DESC", "JX_CHEST")
		Set("체스터의 보금자리.", "RECIPE_DESC", "JX_CHESTER_HOUSE")
		Set("진귀한 보물상자.", "RECIPE_DESC", "JX_CHEST_2")
		Set("유럽풍 금테 접란으로 집을 꾸민다.", "RECIPE_DESC", "JX_CHLOROPHYTUM_COMOSUM_POTTED")
		Set("장식용 꽃꽂이.", "RECIPE_DESC", "JX_COLCHICUM")
		Set("작은 전기 냄비로 더 좋은 음식을 만들 수 있다.", "RECIPE_DESC", "JX_COOKPOT")
		Set("더 빠르게 요리를 완성한다.", "RECIPE_DESC", "JX_COOKPOT_2")
		Set("쓸 만한 한손검.", "RECIPE_DESC", "JX_CROSS_SWORD")
		Set("이 기계로 물건을 분해한다.", "RECIPE_DESC", "JX_DISASSEMBLER")
		Set("바닷바람에 시달려 단단해진 부두 바닥.", "RECIPE_DESC", "JX_DOCK_KIT")
		Set("신사 예복 진열대.", "RECIPE_DESC", "JX_DRESS_FORM_M")
		Set("로리타풍 드레스 진열대.", "RECIPE_DESC", "JX_DRESS_FORM_W")
		Set("예술을 창작하는 도구.", "RECIPE_DESC", "JX_EASEL")
		Set("접힌 날개를 펴서 더위를 식힌다.", "RECIPE_DESC", "JX_FAN")
		Set("농기구를 걸어 두는 나무 선반.", "RECIPE_DESC", "JX_FARM_TOOLS_CONTAINER")
		Set("고전 문장 장식 돌담과 어울리는 난간.", "RECIPE_DESC", "JX_FENCE")
		Set("궁정 조각 돌담과 어울리는 울타리.", "RECIPE_DESC", "JX_FENCE_2")
		Set("성채 칸막이.", "RECIPE_DESC", "JX_FENCE_3")
		Set("아치형 원목 문.", "RECIPE_DESC", "JX_FENCE_GATE")
		Set("방청 도장을 한 소화전.", "RECIPE_DESC", "JX_FIREPLUG")
		Set("잡은 물고기를 잠시 담아 둔다.", "RECIPE_DESC", "JX_FISH_BASKET")
		Set("물건도 넣고 예술적 가치도 있는 골동품 장.", "RECIPE_DESC", "JX_FISH_TANK")
		Set("작은 바다 생태계.", "RECIPE_DESC", "JX_FISH_TANK_2")
		Set("가볍고 쓸모 있는 조명 도구.", "RECIPE_DESC", "JX_FLASHLIGHT")
		Set("꽃잎을 보관하고 작은 꽃벌레를 부른다.", "RECIPE_DESC", "JX_FLOWERCART")
		Set("갓 만든 음식을 판다.", "RECIPE_DESC", "JX_FOOD_TRUCK")
		Set("해변 축구 한판 하자.", "RECIPE_DESC", "JX_FOOTBALL")
		Set("정원의 물 경관.", "RECIPE_DESC", "JX_FOUNTAIN")
		Set("귀엽고 비도 막아 준다.", "RECIPE_DESC", "JX_FROG_RAINCOAT")
		Set("장식용 프런트 데스크.", "RECIPE_DESC", "JX_FRONTDESK")
		Set("친환경 난로.", "RECIPE_DESC", "JX_FURNACE")
		Set("온갖 정교한 인물 피규어를 얻는다.", "RECIPE_DESC", "JX_GACHA_MACHINE")
		Set("딱정벌레 자동차 전용 95 휘발유.", "RECIPE_DESC", "JX_GASOLINE")
		Set("연료를 가득 채운 강철통.", "RECIPE_DESC", "JX_GAS_CANISTER")
		Set("글로머의 보금자리.", "RECIPE_DESC", "JX_GLOMMER_HOUSE")
		Set("힘으로 기적을 만든다.", "RECIPE_DESC", "JX_GOAL")
		Set("페페로미아 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_GREEN_PALM")
		Set("묶음 나뭇가지를 여기에 담는다.", "RECIPE_DESC", "JX_HANDCART")
		Set("정말로 밀 수 있다.", "RECIPE_DESC", "JX_HANDCART_2")
		Set("민속풍 술 장식 해먹.", "RECIPE_DESC", "JX_HANGING_BED")
		Set("술 장식 캐노피가 드리운 안식처.", "RECIPE_DESC", "JX_HANGING_BED_2")
		Set("전통 악기 장식품.", "RECIPE_DESC", "JX_HARP")
		Set("뛰어난 요리 솜씨는 차림새에서도 드러난다.", "RECIPE_DESC", "JX_HAT_COOKER")
		Set("낚시꾼의 모자.", "RECIPE_DESC", "JX_HAT_FISHERMAN")
		Set("흑백 격자 챙모자. 검은 장미와 깃털로 장식했다.", "RECIPE_DESC", "JX_HAT_HEPBURN")
		Set("낡은 냄비. 이제 투구로밖에 못 쓴다.", "RECIPE_DESC", "JX_HAT_IRON_PAN")
		Set("빛나는 군왕의 관.", "RECIPE_DESC", "JX_HAT_KINGCROWN")
		Set("얇은 철판 투구.", "RECIPE_DESC", "JX_HAT_KNIGHT")
		Set("이국적인 멋의 밀짚모자.", "RECIPE_DESC", "JX_HAT_MEXICO")
		Set("길에 나서기 전엔 헬멧부터.", "RECIPE_DESC", "JX_HAT_MOTORCYCLE")
		Set("무척 맛있어 보인다.", "RECIPE_DESC", "JX_HAT_NOODLES")
		Set("따뜻하고 깜찍한 겨울 머리장식.", "RECIPE_DESC", "JX_HAT_REINDEER")
		Set("위압감이 대단한 투구.", "RECIPE_DESC", "JX_HAT_SIGURD")
		Set("캠핑 나갈 때 쓰기 좋은 수제 밀짚모자.", "RECIPE_DESC", "JX_HAT_SUNFLOWER")
		Set("와인빛 궁정풍 둥근 모자.", "RECIPE_DESC", "JX_HAT_WHITE_ROSE")
		Set("풀과 밧줄을 보관한다.", "RECIPE_DESC", "JX_HAY_CART")
		Set("비할 데 없이 예리하다.", "RECIPE_DESC", "JX_HOLY_SWORD")
		Set("달콤한 꿀을 신선하게 지킨다.", "RECIPE_DESC", "JX_HONEY_BOX")
		Set("주방에 빈티지한 멋을 더한다.", "RECIPE_DESC", "JX_ICEBOX")
		Set("크림색 배색의 귀여운 소형 냉장고.", "RECIPE_DESC", "JX_ICEBOX_2")
		Set("깔끔하고 포근한 미색 냉장고.", "RECIPE_DESC", "JX_ICEBOX_3")
		Set("대용량 식품 보관함.", "RECIPE_DESC", "JX_ICEBOX_BIG")
		Set("돌과 제빙기로 얼음을 만든다.", "RECIPE_DESC", "JX_ICEMAKER")
		Set("질 좋은 비망록.", "RECIPE_DESC", "JX_JOURNAL")
		Set("모임에 빠질 수 없는 음식.", "RECIPE_DESC", "JX_KEBAB")
		Set("고전적이고 정교한 유럽 궁정 스탠드.", "RECIPE_DESC", "JX_LAMP")
		Set("은은한 촛불이 고운 이를 비춘다.", "RECIPE_DESC", "JX_LAMP_2")
		Set("흔들리는 불빛이 어둠을 몰아낸다.", "RECIPE_DESC", "JX_LAMP_3")
		Set("장미 모양의 개성 있는 야간등.", "RECIPE_DESC", "JX_LANTERN")
		Set("고성에 대대로 전해 내려온 별빛 등.", "RECIPE_DESC", "JX_LANTERN_2")
		Set("고딕풍의 어둠의 등.", "RECIPE_DESC", "JX_LANTERN_3")
		Set("온갖 가죽을 수납한다.", "RECIPE_DESC", "JX_LEATHER_STORAGE_CHEST")
		Set("비팔로를 기른다.", "RECIPE_DESC", "JX_LIVESTOCKBARN")
		Set("내 저택 문 앞에 고급 우편함을 둔다.", "RECIPE_DESC", "JX_MAILBOX")
		Set("거실 장식으로도 쓸 만하다.", "RECIPE_DESC", "JX_MANTEL_CLOCK")
		Set("냥냥코인과 금덩이를 잠시 보관한다.", "RECIPE_DESC", "JX_MONEYBOX")
		Set("궁정 가로등으로 정원을 밝힌다.", "RECIPE_DESC", "JX_MUSHROOM_LIGHT")
		Set("실내등으로 침실을 꾸민다.", "RECIPE_DESC", "JX_MUSHROOM_LIGHT_2")
		Set("주점 앞 가로등.", "RECIPE_DESC", "JX_MUSHROOM_LIGHT_3")
		Set("폭발하기 쉬운 녹슨 기름통.", "RECIPE_DESC", "JX_OIL_BARREL")
		Set("온갖 재료를 굽고 익힌다.", "RECIPE_DESC", "JX_OVEN")
		Set("음식을 신선하게 지켜 주는 도시락 가방.", "RECIPE_DESC", "JX_PACK")
		Set("진귀한 유화 작품.", "RECIPE_DESC", "JX_PAINTING_MAID")
		Set("미술관이 소장한 유화 작품.", "RECIPE_DESC", "JX_PAINTING_XI")
		Set("당분간은 무기로도 쓸 만하다.", "RECIPE_DESC", "JX_PAN")
		Set("시점을 고정해 운전에 집중한다.\n멀미하는 사람이 없기를.", "RECIPE_DESC", "JX_PARTS_CAMERA_1")
		Set("살짝 똑똑한 기계.\n드리프트 경주에서 쓸모가 있을지도.", "RECIPE_DESC", "JX_PARTS_CAMERA_2")
		Set("새 시즌을 준비할 때다.\n자동차 도색을 바꿔 보자.", "RECIPE_DESC", "JX_PARTS_COLOUR")
		Set("더 강한 힘을 느껴 보자.", "RECIPE_DESC", "JX_PARTS_ENGINE")
		Set("불법 개조한 초고휘도 전조등.\n다만 여기엔 경찰이 없다.", "RECIPE_DESC", "JX_PARTS_LIGHT")
		Set("여행은 결코 외롭지 않다.", "RECIPE_DESC", "JX_PARTS_MUSIC")
		Set("마음이 가는 대로.", "RECIPE_DESC", "JX_PARTS_WHEEL")
		Set("향수백합 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_PERFUME_POTTED")
		Set("펄스 다이얼, 영혼을 몸으로 되돌린다.", "RECIPE_DESC", "JX_PHONOGRAPH")
		Set("고운 피아노 소리가 홀에 울려 퍼진다.", "RECIPE_DESC", "JX_PIANO")
		Set("음식을 절일 수 있다.", "RECIPE_DESC", "JX_PICKLING_BARREL")
		Set("물건을 보관한다.", "RECIPE_DESC", "JX_PLUSHIE_NIGHTSTAND")
		Set("샘물 욕장.", "RECIPE_DESC", "JX_POND")
		Set("야영용 휴대 텐트.", "RECIPE_DESC", "JX_PORTABLETENT")
		Set("야외 요리용 취사도구.", "RECIPE_DESC", "JX_PORTABLE_COOK_POT")
		Set("야외 요리용 취사도구.", "RECIPE_DESC", "JX_PORTABLE_COOK_POT_2")
		Set("브라질나무 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED")
		Set("안스리움 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED_ANTHURIUM")
		Set("베리 화분으로 정원을 꾸민다.", "RECIPE_DESC", "JX_POTTED_BERRY")
		Set("선인장 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED_CACTUS")
		Set("귀여운 토끼 화분에 벚꽃 사랑초를 가득.", "RECIPE_DESC", "JX_POTTED_CHERRY")
		Set("열대 해변의 정취.", "RECIPE_DESC", "JX_POTTED_COCONUT")
		Set("치자꽃 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED_GARDENIA")
		Set("가뭄에 강한 관상용 식물.", "RECIPE_DESC", "JX_POTTED_MEXICO")
		Set("낭만적인 꽃꽂이.", "RECIPE_DESC", "JX_POTTED_MONETPRIMROSE")
		Set("전통 몬스테라 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED_MONSTERA")
		Set("수선화 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED_NARCISSUS")
		Set("장미와 백합의 순수한 사랑.", "RECIPE_DESC", "JX_POTTED_ROSE")
		Set("연회장용 화분.", "RECIPE_DESC", "JX_POTTED_ROSE2")
		Set("산세베리아 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED_SNAKEPLANT")
		Set("대바구니 해바라기 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_POTTED_SUNFLOWER")
		Set("그린프린세스 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_PRINCESS_POTTED")
		Set("정교한 2인 소파.", "RECIPE_DESC", "JX_REDLONGSOFA")
		Set("장미 화분으로 집을 꾸민다.", "RECIPE_DESC", "JX_RED_ROSE_POTTED")
		Set("눈에 아주 잘 띈다.", "RECIPE_DESC", "JX_ROADBLOCK")
		Set("돌과 석재를 보관한다.", "RECIPE_DESC", "JX_ROCK_BIN")
		Set("고급 장미 화분대로 집을 꾸민다.", "RECIPE_DESC", "JX_ROSE_BIG_POTTED")
		Set("집에 실크 태피스트리를 깐다.", "RECIPE_DESC", "JX_RUG_AUBUSSON")
		Set("땅과 카펫을 담아 둘 수 있다.", "RECIPE_DESC", "JX_RUG_BAG")
		Set("체크무늬 실내 융단.", "RECIPE_DESC", "JX_RUG_CASTLEBLUEWHITE")
		Set("무늬가 단아한 현관 매트.", "RECIPE_DESC", "JX_RUG_DOORMAT")
		Set("집에 숲 내음이 나는 사각 카펫을 깐다.", "RECIPE_DESC", "JX_RUG_FOREST")
		Set("집에 타원형 고급 벨벳 카펫을 깐다.", "RECIPE_DESC", "JX_RUG_OVAL")
		Set("집에 호화로운 정원형 카펫을 깐다.", "RECIPE_DESC", "JX_RUG_PLATONI")
		Set("집에 궁정 수제 카펫을 깐다.", "RECIPE_DESC", "JX_RUG_SAVANNAH")
		Set("우아한 무늬가 거실과 침실에 품격을 더한다.", "RECIPE_DESC", "JX_RUG_SOPHIA")
		Set("집에 전통 격자 카펫을 깐다.", "RECIPE_DESC", "JX_RUG_TRADITION")
		Set("집에 민속풍 삼각 카펫을 깐다.", "RECIPE_DESC", "JX_RUG_TRIANGLE")
		Set("등나무로 엮은 전원풍 카펫.", "RECIPE_DESC", "JX_RUG_WOVEN")
		Set("전통 금관악기.", "RECIPE_DESC", "JX_SAXOPHONE")
		Set("밭을 지켜 준다.", "RECIPE_DESC", "JX_SCARECROW")
		Set("개인 물품을 보관한다.", "RECIPE_DESC", "JX_SECURITY_SAFE")
		Set("황금빛 낙엽이 천천히 흩날린다.", "RECIPE_DESC", "JX_SEED_GINKGO")
		Set("넓은 잎을 펼치는 정원 파초나무.", "RECIPE_DESC", "JX_SEED_PLANTAIN")
		Set("재봉틀로 해진 옷을 수선한다.", "RECIPE_DESC", "JX_SEWINGMACHINE")
		Set("연 모양 방패. 공격을 잘 막아 준다.", "RECIPE_DESC", "JX_SHIELD")
		Set("부서진 무기와 도구를 고친다.", "RECIPE_DESC", "JX_SMITHY")
		Set("원목 소파.", "RECIPE_DESC", "JX_SOFA_1")
		Set("장미빛 소파.", "RECIPE_DESC", "JX_SOFA_3")
		Set("북적이는 시장의 작은 좌판.", "RECIPE_DESC", "JX_STALL")
		Set("전원풍 등바구니. 많이 담을 수 있다.", "RECIPE_DESC", "JX_STORAGE_BASKET")
		Set("원목 식탁.", "RECIPE_DESC", "JX_TABLE")
		Set("붉고 정교한 긴 식탁.", "RECIPE_DESC", "JX_TABLE_10")
		Set("거실 장식.", "RECIPE_DESC", "JX_TABLE_11")
		Set("화려하고 우아한 와인장.", "RECIPE_DESC", "JX_TABLE_12")
		Set("장식용 조각 원탁.", "RECIPE_DESC", "JX_TABLE_13")
		Set("조각 장식 주방 조리대.", "RECIPE_DESC", "JX_TABLE_14")
		Set("세면용품을 정리한다.", "RECIPE_DESC", "JX_TABLE_15")
		Set("검붉은 장미를 얹은 팔각 아치문.", "RECIPE_DESC", "JX_TABLE_16")
		Set("좋아하는 요리를 올려 둘 수 있다.", "RECIPE_DESC", "JX_TABLE_2")
		Set("격자 천을 깐 나무 탁자.", "RECIPE_DESC", "JX_TABLE_3")
		Set("많은 사람이 좋아하는 장미빛 식탁.", "RECIPE_DESC", "JX_TABLE_4")
		Set("침실에 정교하고 화려한 화장대를 둔다.", "RECIPE_DESC", "JX_TABLE_5")
		Set("소장품 전시용. 물건을 내렸다가 다시 올려 위치를 조정한다.", "RECIPE_DESC", "JX_TABLE_6")
		Set("장식용 욕실 세면기.", "RECIPE_DESC", "JX_TABLE_7")
		Set("난방과 장식을 겸하는 고급 벽난로.", "RECIPE_DESC", "JX_TABLE_8")
		Set("주방 장식용 개수대.", "RECIPE_DESC", "JX_TABLE_9")
		Set("낡은 카세트에서 흘러나오는 음악을 들어 보자.", "RECIPE_DESC", "JX_TAPEPLAYER")
		Set("클래식 선율을 재생한다.", "RECIPE_DESC", "JX_TAPE_1")
		Set("연회장의 화려하고 유려한 곡을 담았다.", "RECIPE_DESC", "JX_TAPE_2")
		Set("한여름 숲의 나른한 선율을 봉인했다.", "RECIPE_DESC", "JX_TAPE_3")
		Set("옛 시절을 그대로 옮긴 전화부스.", "RECIPE_DESC", "JX_TELEPHONE_BOOTH")
		Set("호화로운 유럽풍 돔형 침대.\n일반 텐트보다 오래간다.", "RECIPE_DESC", "JX_TENT")
		Set("온열석 대신 토스터를 쓴다.", "RECIPE_DESC", "JX_TOASTER")
		Set("흡입력이 어마어마해서 카펫도 빨아들인다.", "RECIPE_DESC", "JX_TOILET_SUCTION")
		Set("파란색 철제 쓰레기통.", "RECIPE_DESC", "JX_TRASH_CAN")
		Set("게임기가 달린 빈티지 텔레비전.", "RECIPE_DESC", "JX_TV")
		Set("햇빛도 비도 막아 주는 고양이귀 우산.", "RECIPE_DESC", "JX_UMBRELLA")
		Set("벼락을 막아 준다.", "RECIPE_DESC", "JX_UTILITY_POLE")
		Set("음료수나 한잔 뽑자.", "RECIPE_DESC", "JX_VENDING_MACHINE")
		Set("온갖 옷과 장신구를 넣어 둔다.", "RECIPE_DESC", "JX_WARDROBE")
		Set("손에 아주 잘 맞는 괭이.\n구덩이를 특히 빨리 판다.", "RECIPE_DESC", "JX_WAR_HOE")
		Set("세탁기로 옷을 빨고 말린다.", "RECIPE_DESC", "JX_WASHER")
		Set("알라딘이 물을 만들어 주는 마법.", "RECIPE_DESC", "JX_WATERINGCAN")
		Set("끝이 날카로운 포크.", "RECIPE_DESC", "JX_WEAPON_1")
		Set("잘 드는 나이프.", "RECIPE_DESC", "JX_WEAPON_2")
		Set("오늘 저녁은 내가 맡지.", "RECIPE_DESC", "JX_WEAPON_3")
		Set("따개가 없다.", "RECIPE_DESC", "JX_WEAPON_4")
		Set("주방장이 쓰는 뒤집개.", "RECIPE_DESC", "JX_WEAPON_5")
		Set("통나무를 깎아 만든 주걱.", "RECIPE_DESC", "JX_WEAPON_6")
		Set("채소도 뼈도 자른다.", "RECIPE_DESC", "JX_WEAPON_7")
		Set("제과용 조리도구.", "RECIPE_DESC", "JX_WEAPON_8")
		Set("제과용 조리도구.", "RECIPE_DESC", "JX_WEAPON_9")
		Set("쓸모 있는 돌우물.", "RECIPE_DESC", "JX_WELL")
		Set("가구 전체를 다룬 공략서.", "RECIPE_DESC", "JX_WIKI_BOOK")
		Set("삐걱대며 도는 풍차.", "RECIPE_DESC", "JX_WINDMILL")
		Set("나무를 보관한다.", "RECIPE_DESC", "JX_WOOD_BIN")
		Set("집에서 귀여운 치즈냥이를 기른다.", "RECIPE_DESC", "JX_XUNCAT")
		Set("진귀한 상품.", "RECIPE_DESC", "JX_XUNCAT_SUPERBIGCUP")
		Set("욕실 타일을 새것으로 바꾼다.", "RECIPE_DESC", "TURF_BATH")
		Set("곱게 짠 기모 빈티지 카펫.", "RECIPE_DESC", "TURF_CORRIDOR")
		Set("쪽매 카펫은 집 꾸미기에 좋은 선택이다.", "RECIPE_DESC", "TURF_GRANITE")
		Set("말끔하게 맞춘 시멘트 블록.", "RECIPE_DESC", "TURF_JX_COURTYARD")
		Set("잿빛 기하 직조 무늬 석재 타일.", "RECIPE_DESC", "TURF_JX_COURTYARD2")
		Set("보도용 마름모 타일.", "RECIPE_DESC", "TURF_JX_GREENDIAMOND")
		Set("오래된 저택의 바닥 타일.", "RECIPE_DESC", "TURF_JX_MANSION")
		Set("보도용 바닥 타일.", "RECIPE_DESC", "TURF_JX_WHITESQUARE")
		Set("정밀하게 짜 맞춘 원목 마루.", "RECIPE_DESC", "TURF_JX_WOOD")
		Set("고급 시공 티크 마루.", "RECIPE_DESC", "TURF_JX_WOOD2")
		Set("침실에 붉은 카펫을 깐다.", "RECIPE_DESC", "TURF_REDDISH_BROWN")
		Set("고전 저택의 석조 담기둥.", "RECIPE_DESC", "WALL_JX_STONE")
		Set("궁정에서 흔히 쓰는 조각 돌담.", "RECIPE_DESC", "WALL_JX_STONE_2")
		Set("어두운 분위기의 조각 담장.", "RECIPE_DESC", "WALL_JX_STONE_3")
		Set("중세풍 벽체.", "RECIPE_DESC", "WALL_JX_STONE_4")
		Set("조경용 가림벽.", "RECIPE_DESC", "WALL_JX_STONE_5")
		Set("정원 조경용 생울타리.", "RECIPE_DESC", "WALL_JX_STRAW_1")
		Set("검붉은 장미를 얹은 빈티지 예장 기둥.", "RECIPE_DESC", "WALL_JX_WOOD_1")
		Set("자동차 창고", "UI", "CRAFTING_FILTERS", "JXCARTAB")
		Set("징시 가구 꾸러미", "UI", "CRAFTING_FILTERS", "JXTAB")
		Set("감상 모드", "UI", "JX_PIANO_APPRECIATE")
		Set("돌아가기", "UI", "JX_PIANO_BACK")
		Set("클래식 피아노", "UI", "JX_PIANO_CLASSICAL")
		Set("닫기", "UI", "JX_PIANO_CLOSE")
		Set("자유 연주", "UI", "JX_PIANO_FREEPLAY")
		Set("다음 쪽", "UI", "JX_PIANO_PAGE_DOWN")
		Set("이전 쪽", "UI", "JX_PIANO_PAGE_UP")
		Set("대중 피아노", "UI", "JX_PIANO_POPULAR")
		Set("무작위", "UI", "JX_PIANO_RANDOM")
		Set("저장", "UI", "JX_PIANO_SAVE")
		Set("재생 중지", "UI", "JX_PIANO_STOP_MUSIC")
		Set("음량", "UI", "JX_PIANO_VOLUME")
		Set("음량 -", "UI", "JX_PIANO_VOLUMEDOWN")
		Set("음량 +", "UI", "JX_PIANO_VOLUMEUP")
	end end)

	-- Pond OceanTree  (workshop-3675508496)  129개
	pcall(function() if Apply("3675508496") then
		Set("혹덩이 열매 넣기", "ACTIONS", "HEAVY_THROW")
		Set("안 돼.", "CHARACTERS", "GENERIC", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("여긴 이미 물속나무가 있어. 과학적으로 심어야지.", "CHARACTERS", "GENERIC", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("여긴 너무 좁아. 물속나무가 제대로 자랄 수 없어. 먼저 좀 더 파내야겠군.", "CHARACTERS", "GENERIC", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("이 온천은 너무 작아. 더 큰 곳을 찾아보자.", "CHARACTERS", "GENERIC", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("과학적으로 보면, 이제 무화과 즙만 빨아먹는군.", "CHARACTERS", "GENERIC", "DESCRIBE", "FIG_MOSQUITO")
		Set("무화과를 너무 많이 먹은 개구리다. 귀엽군!", "CHARACTERS", "GENERIC", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WALTER", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("플로릅, 여긴 벌써 임자가 있어!", "CHARACTERS", "WALTER", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("플로릅, 너무 좁아, 먼저 파!", "CHARACTERS", "WALTER", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("플로릅, 너무 좁아, 더 큰 데 찾아!", "CHARACTERS", "WALTER", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("적어도 이 녀석은 온몸을 가렵게 하진 않아.", "CHARACTERS", "WALTER", "DESCRIBE", "FIG_MOSQUITO")
		Set("내 안내서에 있는 개구리랑은 안 닮았는데... 그래도 친근하네.", "CHARACTERS", "WALTER", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WANDA", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("귀찮게시리, 이 웅덩이엔 자리가 없잖아!", "CHARACTERS", "WANDA", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("귀찮게시리, 너무 좁아서 파는 데 시간까지 버려야 하다니!", "CHARACTERS", "WANDA", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("귀찮게시리, 너무 좁아서 다른 데 찾는 데 시간을 버려야 하다니!", "CHARACTERS", "WANDA", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("이젠 무화과 즙만 짜내려 해서 다행이야. 예전보단 훨씬 낫지.", "CHARACTERS", "WANDA", "DESCRIBE", "FIG_MOSQUITO")
		Set("딱 봐도 억지로 붙여 놓은 거잖아. 엉망진창이군.", "CHARACTERS", "WANDA", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WARLY", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("가득 찬 냄비에 재료를 더 넣진 않잖아요?", "CHARACTERS", "WARLY", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("웅덩이가 작아서 이걸 못 담아요. 단 요리 좀 먹고 파냅시다!", "CHARACTERS", "WARLY", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("이 온천은 이 열매를 누릴 복이 없나 보군요. 더 큰 데를 찾읍시다.", "CHARACTERS", "WARLY", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("저 녀석에게 무화과 즙은 음료수 같은 것이겠죠.", "CHARACTERS", "WARLY", "DESCRIBE", "FIG_MOSQUITO")
		Set("세상에, 이렇게 눈치 빠른 식재료가 다 있나요?", "CHARACTERS", "WARLY", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WATHGRITHR", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("저 안의 것과 고난을 함께할 생각은 없는 모양이군.", "CHARACTERS", "WATHGRITHR", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("이 물웅덩이는 아직 좁다. 동료들과 삽으로 넓혀야겠군.", "CHARACTERS", "WATHGRITHR", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("아직 너무 좁구나. 동료들을 위해 더 큰 곳을 찾아야겠다.", "CHARACTERS", "WATHGRITHR", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("전보다 더 쓸모가 없어졌구나!", "CHARACTERS", "WATHGRITHR", "DESCRIBE", "FIG_MOSQUITO")
		Set("그 성가신 고기 아닌 것이 이 개구리를 너무 차지하지 않았기를.", "CHARACTERS", "WATHGRITHR", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WATHOM", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("동종 개체 존재.", "CHARACTERS", "WATHOM", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("협소. 확장 필요.", "CHARACTERS", "WATHOM", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("협소. 다른 웅덩이로 전환 필요.", "CHARACTERS", "WATHOM", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("무해. 분홍 벌레.", "CHARACTERS", "WATHOM", "DESCRIBE", "FIG_MOSQUITO")
		Set("무해. 분홍 고기.", "CHARACTERS", "WATHOM", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WAXWELL", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("나와 윌슨이 보기에 여긴 두 번째를 들일 공간이 없군.", "CHARACTERS", "WAXWELL", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("보아하니 물이 아직 넉넉지 않군. 하인을 시켜 파게 하지.", "CHARACTERS", "WAXWELL", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("흥, 물이 아직 넉넉지 않군. 다른 데를 더 찾아보지.", "CHARACTERS", "WAXWELL", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("얘들아, 이건 정말 내가 한 게 아니란다.", "CHARACTERS", "WAXWELL", "DESCRIBE", "FIG_MOSQUITO")
		Set("날 보지 마라. 내가 한 게 아니야.", "CHARACTERS", "WAXWELL", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WEBBER", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("우리 눈에 안에 있는 게 보여. 이러면 안 돼.", "CHARACTERS", "WEBBER", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("웅덩이가 너무 좁은 것 같아. 삽으로 한바탕 파야겠어.", "CHARACTERS", "WEBBER", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("웅덩이가 너무 좁은 것 같아. 더 큰 데를 찾아야겠어.", "CHARACTERS", "WEBBER", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("바다거미 친구들이 이걸 좋아할 것 같아.", "CHARACTERS", "WEBBER", "DESCRIBE", "FIG_MOSQUITO")
		Set("혀는 여전히 끈적하지만, 적어도 우릴 핥진 않아!", "CHARACTERS", "WEBBER", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WENDY", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("아쉽게도, 먼저 온 자가 이미 차지했구나.", "CHARACTERS", "WENDY", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("더 파내기 전엔 이 나무를 품을 수 없어. 참 슬픈 일이야.", "CHARACTERS", "WENDY", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("너무 좁아. 저 안에서 자라려면 몹시 괴로울 거야.", "CHARACTERS", "WENDY", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("무화과의 즙을 훔쳐 제 목숨을 이어 가는구나.", "CHARACTERS", "WENDY", "DESCRIBE", "FIG_MOSQUITO")
		Set("애비게일이 그러는데 벌도 잔뜩 먹었대.", "CHARACTERS", "WENDY", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WICKERBOTTOM", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("이보세요, 여긴 이미 나무가 한 그루 있답니다.", "CHARACTERS", "WICKERBOTTOM", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("이보세요, 삽으로 웅덩이를 넓힌 뒤에 시도하는 게 좋겠군요.", "CHARACTERS", "WICKERBOTTOM", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("이보세요, 이 온천은 물속나무가 자라기에 크기가 턱없이 모자랍니다.", "CHARACTERS", "WICKERBOTTOM", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("몹시 굶주린 암컷 흡... 즙 모기로군요?", "CHARACTERS", "WICKERBOTTOM", "DESCRIBE", "FIG_MOSQUITO")
		Set("일종의... 음, 무화과와 융합된 개구리군요? 구우면 맛있을 것도 같습니다.", "CHARACTERS", "WICKERBOTTOM", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WILLOW", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("안에 있는 저거 먼저 태워 버릴까?", "CHARACTERS", "WILLOW", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("너무 작아, 너무 작다고! 먼저 좀 파내!", "CHARACTERS", "WILLOW", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("이 작은 온천 마음에 드는데, 이 덩치한테는 너무 좁아.", "CHARACTERS", "WILLOW", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("이제 저 무화과나 괴롭히러 가!", "CHARACTERS", "WILLOW", "DESCRIBE", "FIG_MOSQUITO")
		Set("여전히 불은 안 붙네... 그래도 그 징그러운 초록색은 아니잖아.", "CHARACTERS", "WILLOW", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WINKY", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("이 자리엔 다른 게 들어 있어!", "CHARACTERS", "WINKY", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("너무 좁아. 가족들한테 좀 파 달라고 하자.", "CHARACTERS", "WINKY", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("너무 좁아. 가족들한테 더 큰 데를 찾아 달라고 하자.", "CHARACTERS", "WINKY", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("우리 사이좋게 지낼 수 있으면 좋겠어.", "CHARACTERS", "WINKY", "DESCRIBE", "FIG_MOSQUITO")
		Set("즙도 많고 살도 있는데 때리지도 않아!", "CHARACTERS", "WINKY", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WINONA", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("이 \"받침대\"엔 벌써 나무가 있잖아!", "CHARACTERS", "WINONA", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("나쁜 소식은 웅덩이 크기가 안 맞는다는 거고, 좋은 소식은 내가 삽질도 잘한다는 거지.", "CHARACTERS", "WINONA", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("하... 웅덩이 크기가 안 맞네. 더 큰 데를 찾자.", "CHARACTERS", "WINONA", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("어... 빈대보단 확실히 기괴하네.", "CHARACTERS", "WINONA", "DESCRIBE", "FIG_MOSQUITO")
		Set("그래, 그냥... 어, 과일 개구리?", "CHARACTERS", "WINONA", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WIRLYWINGS", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("음, 이미 다른 나무가 있어.", "CHARACTERS", "WIRLYWINGS", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("음, 웅덩이가 좁은데, 삽으로 먼저 넓혀 볼까?", "CHARACTERS", "WIRLYWINGS", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("음, 웅덩이가 좁아. 다른 데를 찾아보자.", "CHARACTERS", "WIRLYWINGS", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("음, 조금만 더 붉으면 체리 같겠는데.", "CHARACTERS", "WIRLYWINGS", "DESCRIBE", "FIG_MOSQUITO")
		Set("음, 그대로 냄비에 쪄서 밥으로 만들어도 되겠어.", "CHARACTERS", "WIRLYWINGS", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WIXIE", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("웅덩이 안에 있는 저건 어쩔 도리가 없는 것 같아.", "CHARACTERS", "WIXIE", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("딱 봐도 안 되겠는데. 삽으로 먼저 파서 넓혀야겠어.", "CHARACTERS", "WIXIE", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("너무 좁아. 월터한테 더 큰 데를 찾아 달라고 하자.", "CHARACTERS", "WIXIE", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("더 통통해진 즙 터지는 과녁이야.", "CHARACTERS", "WIXIE", "DESCRIBE", "FIG_MOSQUITO")
		Set("탄환 한 방이면 배가 터지겠는걸.", "CHARACTERS", "WIXIE", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WOLFGANG", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("안에 이미 나무 있다. 볼프강 하나 더 못 넣는다.", "CHARACTERS", "WOLFGANG", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("너무 작다. 먼저 파낸다. 볼프강 금방 할 수 있다!", "CHARACTERS", "WOLFGANG", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("볼프강 생각한다, 이 뜨거운 물 너무 작다. 큰 걸로 바꾼다.", "CHARACTERS", "WOLFGANG", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("볼프강 삼촌은 분홍색 아니다.", "CHARACTERS", "WOLFGANG", "DESCRIBE", "FIG_MOSQUITO")
		Set("헤이... 분홍 개구리다!", "CHARACTERS", "WOLFGANG", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WOODIE", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("자리가 없어! 저놈부터 베어 버릴까?", "CHARACTERS", "WOODIE", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("루시 말로는 자리가 좁대. 삽부터 들고 한바탕 파 보자고!", "CHARACTERS", "WOODIE", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("루시 말로는 자리가 좁대. 다른 샘을 찾아보자.", "CHARACTERS", "WOODIE", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("저놈이 무화과 즙을 한 파인트나 빨아먹었어!", "CHARACTERS", "WOODIE", "DESCRIBE", "FIG_MOSQUITO")
		Set("늘 하는 말이지만, 물에서 살지 육지에서 살지도 못 정하는 동물은 못 믿겠어.", "CHARACTERS", "WOODIE", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WORMWOOD", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("큰 친구가 벌써 살고 있어.", "CHARACTERS", "WORMWOOD", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("사는 곳이 좁아. 큰 친구 싫어해. 파는 도구로 먼저 넓히기.", "CHARACTERS", "WORMWOOD", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("이 뜨거운 물, 살 자리 너무 좁아. 친구는 더 큰 게 필요해.", "CHARACTERS", "WORMWOOD", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("분홍 윙윙.", "CHARACTERS", "WORMWOOD", "DESCRIBE", "FIG_MOSQUITO")
		Set("분홍 개굴.", "CHARACTERS", "WORMWOOD", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WORTOX", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("같은 웅덩이엔 못 들어가!", "CHARACTERS", "WORTOX", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("웅덩이가 좁아 못 담네, 어서 파내자!", "CHARACTERS", "WORTOX", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("웅덩이가 좁아 못 담네, 다른 데를 찾자!", "CHARACTERS", "WORTOX", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("이보게, 나한텐 빨아먹을 즙 같은 건 없다네.", "CHARACTERS", "WORTOX", "DESCRIBE", "FIG_MOSQUITO")
		Set("너무 배불리 먹어서 뜀박질이 굼뜨구나!", "CHARACTERS", "WORTOX", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WURT", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("플로릅, 여긴 벌써 임자가 있어!", "CHARACTERS", "WURT", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("플로릅, 너무 좁아, 먼저 파!", "CHARACTERS", "WURT", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("플로릅, 너무 좁아, 더 큰 데 찾아!", "CHARACTERS", "WURT", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("플로릅, 무화과를 빨게 해서 키우면 쓸모 있어!", "CHARACTERS", "WURT", "DESCRIBE", "FIG_MOSQUITO")
		Set("플로릅, 널 먹고 싶어!", "CHARACTERS", "WURT", "DESCRIBE", "FIOG")
		Set("안 돼.", "CHARACTERS", "WX78", "ACTIONFAIL", "HEAVY_THROW", "GENERIC")
		Set("대상 수역 용량 초과.", "CHARACTERS", "WX78", "ACTIONFAIL", "HEAVY_THROW", "HASOCEANTREE")
		Set("접속부 호환 불가. 확장 개조 필요.", "CHARACTERS", "WX78", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE")
		Set("접속부 호환 불가. 더 큰 대상으로 전환 요청.", "CHARACTERS", "WX78", "ACTIONFAIL", "HEAVY_THROW", "IRREPLACEABLE2")
		Set("유기체의 생명을 빨아들이던 시절이 더 마음에 들었다.", "CHARACTERS", "WX78", "DESCRIBE", "FIG_MOSQUITO")
		Set("이 우스꽝스러운 유기체는 무화과 개구리 다리 샌드위치가 될 수 있다.", "CHARACTERS", "WX78", "DESCRIBE", "FIOG")
		Set("친근한 모기", "NAMES", "FIG_MOSQUITO")
		Set("무화과 개구리", "NAMES", "FIOG")
	end end)

	-- DST Coffee and More  (workshop-2981932326)  60개
	pcall(function() if Apply("2981932326") then
		Set("자, 진짜 문제는 이거다. 이걸 어떻게 커피로 만들지?", "CHARACTERS", "GENERIC", "DESCRIBE", "COFFEEBEANS")
		Set("이제 먹을 수는 있겠군. 하지만... 내 커피는...", "CHARACTERS", "GENERIC", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("잠깐... 커피나무? 여기에? 자기가 어느 지역에 있는지는 아는 건가?", "CHARACTERS", "GENERIC", "DESCRIBE", "COFFEEBUSH")
		Set("냄새 좋군.", "CHARACTERS", "GENERIC", "DESCRIBE", "COFFEE_GROUND")
		Set("내 농장의 시작이다.", "CHARACTERS", "GENERIC", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("이 콩으로 무엇을 하길 원하시는지 프레이르께 여쭈어야겠다.", "CHARACTERS", "WATHGRITHR", "DESCRIBE", "COFFEEBEANS")
		Set("그들의 희생은 잊히지 않으리라.", "CHARACTERS", "WATHGRITHR", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("프레이르께서 그대에게 축복을 내리셨구나, 커피나무여.", "CHARACTERS", "WATHGRITHR", "DESCRIBE", "COFFEEBUSH")
		Set("프레이르를 기쁘게 하려면 심어야 하리라.", "CHARACTERS", "WATHGRITHR", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("하! 바리스타는 정작 필요할 때 어디 있는 건가?!", "CHARACTERS", "WAXWELL", "DESCRIBE", "COFFEEBEANS")
		Set("손이 이렇게 많이 가니 커피가 싫어지기 시작하는군.", "CHARACTERS", "WAXWELL", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("여기서 카페에 가장 가까운 것이라고 해야겠지.", "CHARACTERS", "WAXWELL", "DESCRIBE", "COFFEEBUSH")
		Set("고작 한 잔을 위해 이런 수고까지 해야 하다니...", "CHARACTERS", "WAXWELL", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("아빠는 콩을 이렇게 그냥 먹진 않았던 것 같은데.", "CHARACTERS", "WEBBER", "DESCRIBE", "COFFEEBEANS")
		Set("엄마가 아빠 커피 내릴 때 쓰던 거랑 좀 비슷해.", "CHARACTERS", "WEBBER", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("아빠가 마시던 커피 냄새가 나!", "CHARACTERS", "WEBBER", "DESCRIBE", "COFFEEBUSH")
		Set("정원 가꾸러 가자!", "CHARACTERS", "WEBBER", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("검은 액체에 대한 갈증을 달래기 위해 이것들을 바치겠어.", "CHARACTERS", "WENDY", "DESCRIBE", "COFFEEBEANS")
		Set("너희는 죽었어. 공식적으로.", "CHARACTERS", "WENDY", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("저 열매로 커피를 내릴 수 있겠지. 가장 깊은 지하감옥처럼 새까만.", "CHARACTERS", "WENDY", "DESCRIBE", "COFFEEBUSH")
		Set("이걸 키워 볼까, 애비게일?", "CHARACTERS", "WENDY", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("잘 여문 비열개성 핵과로군요.", "CHARACTERS", "WICKERBOTTOM", "DESCRIBE", "COFFEEBEANS")
		Set("이 상태로 먹을 만큼 제가 사향고양이는 아니랍니다.", "CHARACTERS", "WICKERBOTTOM", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("코페아속의 일종이 이곳 기후에 적응한 모양이군요.", "CHARACTERS", "WICKERBOTTOM", "DESCRIBE", "COFFEEBUSH")
		Set("이곳 기후가 맞는지 한번 봅시다.", "CHARACTERS", "WICKERBOTTOM", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("내 행운의 라이터를 소개하지. 탈 준비 해!", "CHARACTERS", "WILLOW", "DESCRIBE", "COFFEEBEANS")
		Set("참 곱게도 탔네. 훌륭해, 작은 콩들아.", "CHARACTERS", "WILLOW", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("이 어색한 시간은 건너뛰고 바로 콩 태우는 걸로 가면 안 될까?", "CHARACTERS", "WILLOW", "DESCRIBE", "COFFEEBUSH")
		Set("커피콩을 태우려면 일단 이걸 심어야 해.", "CHARACTERS", "WILLOW", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("우웩. 볼프강 일 더 해야 한다.", "CHARACTERS", "WOLFGANG", "DESCRIBE", "COFFEEBEANS")
		Set("여전히 쓰다, 그래도 좋다.", "CHARACTERS", "WOLFGANG", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("우웩, 저 열매들! 날것은 너무 쓰다!", "CHARACTERS", "WOLFGANG", "DESCRIBE", "COFFEEBUSH")
		Set("내가 심는다, 너는 커피 준다.", "CHARACTERS", "WOLFGANG", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("아직 커피랑 스콘을 즐길 때는 아니야, 루시...", "CHARACTERS", "WOODIE", "DESCRIBE", "COFFEEBEANS")
		Set("먹을 만해 보이는데, 안 그래?", "CHARACTERS", "WOODIE", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("이 친구한테서 은은하게 커피 향이 나는군.", "CHARACTERS", "WOODIE", "DESCRIBE", "COFFEEBUSH")
		Set("이 친구만 있으면 우리 커피를 직접 길러 먹을 수 있어.", "CHARACTERS", "WOODIE", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("살덩이들은 모든 것을 복잡하게 만든다.", "CHARACTERS", "WX78", "DESCRIBE", "COFFEEBEANS")
		Set("열등한 연료 변종.", "CHARACTERS", "WX78", "DESCRIBE", "COFFEEBEANS_COOKED")
		Set("실험용 연료 식물.", "CHARACTERS", "WX78", "DESCRIBE", "COFFEEBUSH")
		Set("커피 기반 연료 설계도.", "CHARACTERS", "WX78", "DESCRIBE", "DUG_COFFEEBUSH")
		Set("블랙커피", "NAMES", "BLACK_COFFEE")
		Set("카페인", "NAMES", "CAFFEINE")
		Set("카푸치노", "NAMES", "CAPPUCCINO")
		Set("카라멜 마키아토", "NAMES", "CARAMEL_MACCHIATO")
		Set("커피", "NAMES", "COFFEE")
		Set("커피콩", "NAMES", "COFFEEBEANS")
		Set("구운 커피콩", "NAMES", "COFFEEBEANS_COOKED")
		Set("커피나무", "NAMES", "COFFEEBUSH")
		Set("커피 햄", "NAMES", "COFFEEHAM")
		Set("커피 필터", "NAMES", "COFFEE_FILTER")
		Set("곱게 간 커피", "NAMES", "COFFEE_GROUND")
		Set("커피 밀크셰이크", "NAMES", "COFFEE_MILKSHAKE")
		Set("캐낸 커피나무", "NAMES", "DUG_COFFEEBUSH")
		Set("에스프레소", "NAMES", "ESPRESSO")
		Set("프라페", "NAMES", "FRAPPE")
		Set("아이스커피", "NAMES", "ICED_COFFEE")
		Set("라떼", "NAMES", "LATTE")
		Set("고급 셰이커", "NAMES", "SHAKER_GOLD")
		Set("나무 셰이커", "NAMES", "SHAKER_WOOD")
	end end)

	-- [API] Modded Skins  (workshop-2812783478)  53개
	pcall(function() if Apply("2812783478") then
		Set("이 모드 제작자가 해금 조건을 안 적어 놓은 것 같습니다...", "MODSKINUNLOCK_REQUIREMENT", "MISSING")
		Set("이 스킨을 쓰려면 원본 '%s %s' 스킨을 가지고 있어야 합니다.", "MODSKINUNLOCK_REQUIREMENT", "OFFICIALREQUIRED")
		Set("모드로 만들어진 스킨입니다!", "SKIN_DESCRIPTIONS", "MS_DEFAULT")
		Set("붉은새 빛깔의 캣아이 선글라스. 한여름 햇빛을 막아 주진 못하지만 도도한 고양이 느낌은 확실합니다!", "SKIN_DESCRIPTIONS", "ms_glasses_catshade")
		Set("하트 모양 안경. 그대의 심장 펌프 기관이 뛰고 있다는 걸 알리기에 완벽합니다!", "SKIN_DESCRIPTIONS", "ms_glasses_heartstruck")
		Set("파랑새 빛깔의 뾰족한 선글라스. 진지하게 임하고 있다는 걸 알리기에 딱 좋은 각도입니다.", "SKIN_DESCRIPTIONS", "ms_glasses_pointedshade")
		Set("터치스톤 빛깔의 검은 선글라스. 지독하게 타오르는 저 태양으로부터 약한 눈을 지켜 줍니다.", "SKIN_DESCRIPTIONS", "ms_glasses_shades")
		Set("접이식 렌즈로 초점을 정밀하게 맞출 수 있습니다.", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_bishop")
		Set("이 \"시계 단안경\"은 앞이 안 보이지만, 사람들의 눈은 확실히 사로잡습니다!", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_formal")
		Set("콘스턴트의 혹독한 겨울은 준비 없는 눈에게 결코 친절하지 않습니다.", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_ice")
		Set("밤 너머 다른 존재의 꿈을 들여다봅니다.", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_lunar")
		Set("생분해 소재로 만들었습니다. 시대를 백 년은 앞서갑니다!", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_nature")
		Set("어두워진 렌즈 너머로 미래를 봅니다.", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_shadow")
		Set("시간지기의 머리카락이 아직 몇 올 붙어 있습니다.", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_steampunk")
		Set("콘스턴트는 가혹하지만, 남을 위해 정교한 장난감을 만들다 보면 사람다움을 되찾게 됩니다.", "SKIN_DESCRIPTIONS", "ms_glasses_wanda_yule")
		Set("디어클롭스에게 이 차림을 보여 주세요. 감탄해서 봐줄지도 모릅니다!", "SKIN_DESCRIPTIONS", "ms_glasses_wathgrithr_deerclops")
		Set("광기와 과학이 뒤섞일 준비를 하세요!", "SKIN_DESCRIPTIONS", "ms_glasses_wilson_madscience")
		Set("초목을 더 또렷하게 관찰할 수 있습니다.", "SKIN_DESCRIPTIONS", "ms_glasses_wilson_nature")
		Set("돼지들이 이 차림을 재미있어 해 주기를 바라는 수밖에.", "SKIN_DESCRIPTIONS", "ms_glasses_wilson_pigguard")
		Set("아픈 눈에 위안이 되는 물건.", "SKIN_DESCRIPTIONS", "ms_glasses_wilson_survivor")
		Set("모드제", "SKIN_NAMES", "MS_DEFAULT")
		Set("캣아이 선글라스", "SKIN_NAMES", "ms_glasses_catshade")
		Set("하트 안경", "SKIN_NAMES", "ms_glasses_heartstruck")
		Set("뾰족 선글라스", "SKIN_NAMES", "ms_glasses_pointedshade")
		Set("검은 선글라스", "SKIN_NAMES", "ms_glasses_shades")
		Set("태엽 비숍 렌즈", "SKIN_NAMES", "ms_glasses_wanda_bishop")
		Set("빛나는 시계 단안경", "SKIN_NAMES", "ms_glasses_wanda_formal")
		Set("북극 탐험가의 고글", "SKIN_NAMES", "ms_glasses_wanda_ice")
		Set("점술가의 안경", "SKIN_NAMES", "ms_glasses_wanda_lunar")
		Set("자연주의자 안경", "SKIN_NAMES", "ms_glasses_wanda_nature")
		Set("그림자 렌즈", "SKIN_NAMES", "ms_glasses_wanda_shadow")
		Set("땜장이의 고글", "SKIN_NAMES", "ms_glasses_wanda_steampunk")
		Set("장난감 장인의 안경", "SKIN_NAMES", "ms_glasses_wanda_yule")
		Set("디어클롭스 렌즈", "SKIN_NAMES", "ms_glasses_wathgrithr_deerclops")
		Set("미친 실험실 고글", "SKIN_NAMES", "ms_glasses_wilson_madscience")
		Set("식물학자의 안경", "SKIN_NAMES", "ms_glasses_wilson_nature")
		Set("돼지 경비병 코", "SKIN_NAMES", "ms_glasses_wilson_pigguard")
		Set("안대", "SKIN_NAMES", "ms_glasses_wilson_survivor")
		Set("이 장식품은 모드로 추가된 것입니다.", "UI", "BARTERSCREEN", "COMMERCE_INFO_ISMODDED")
		Set("마법이 더 필요합니다!", "UI", "ITEM_SCREEN", "DISABLED_MODDEDTOAST_TOOLTIP")
		Set("스킨 해금 조건", "UI", "MODLOCKED")
		Set("%s 님이 새 모드 스킨을 얻었습니다: ", "UI", "NOTIFICATION", "NEW_MODSKIN_ANNOUNCEMENT")
		Set("맞춤", "UI", "RARITY", "ModLocked")
		Set("제작됨", "UI", "RARITY", "ModMade")
		Set("화려함", "UI", "RARITY", "ModOfficialRequired")
		Set("모드 - ", "UI", "RARITY", "Modded")
		Set("안경", "UI", "WARDROBESCREEN", "GLASSES")
		Set("모드 스킨 숨기기: {mode}", "UI", "WARDROBESCREEN", "MODDED_FILTER_FMT")
		Set("출처 모드", "UI", "WARDROBESCREEN", "MODLINK_MOREINFO")
		Set("스킨 해금 조건", "UI", "WARDROBESCREEN", "MODLOCKEDREQUIREMENTS")
		Set("닫기", "UI", "WARDROBESCREEN", "MODLOCKEDREQUIREMENTS_CLOSE")
		Set("공식 스킨 숨기기: {mode}", "UI", "WARDROBESCREEN", "OFFICIAL_FILTER_FMT")
		Set("안경을 착용합니다", "UI", "WARDROBESCREEN", "TOOLTIP_GLASSES")
	end end)

	-- Shadow Field Exciter  (workshop-3466003439)  22개
	pcall(function() if Apply("3466003439") then
		Set("그림자가 대신 정리해 주는군.", "CHARACTERS", "GENERIC", "DESCRIBE", "SHADOWFIELDEXCITER")
		Set("지금 설정을 새 프리셋으로 저장", "MOD_ShadowFieldExciter", "Btn_AddPreset_ToolTip")
		Set("블랙리스트 비우기", "MOD_ShadowFieldExciter", "Btn_ClearBlackList_ToolTip")
		Set("화이트리스트 비우기", "MOD_ShadowFieldExciter", "Btn_ClearWhiteList_ToolTip")
		Set("닫기", "MOD_ShadowFieldExciter", "Btn_Close_ToolTip")
		Set("저장하고 동기화", "MOD_ShadowFieldExciter", "Btn_SaveAndSync_ToolTip")
		Set("부적 제외", "MOD_ShadowFieldExciter", "IgnoreAmulet")
		Set("방어구 제외", "MOD_ShadowFieldExciter", "IgnoreArmor")
		Set("음식 제외", "MOD_ShadowFieldExciter", "IgnoreFood")
		Set("제외할 것...", "MOD_ShadowFieldExciter", "IgnoreSomething")
		Set("겹치지 않는 물건 제외", "MOD_ShadowFieldExciter", "IgnoreUnStackable")
		Set("무기 제외", "MOD_ShadowFieldExciter", "IgnoreWeapon")
		Set("다른 사람이 설정 중입니다", "MOD_ShadowFieldExciter", "MSG_OpenTips")
		Set("판정 방식", "MOD_ShadowFieldExciter", "MatchMode")
		Set("프리셋 \"%s\" 이(가) 이미 있습니다. 덮어쓸까요?", "MOD_ShadowFieldExciter", "PresetExists")
		Set("프리셋 \"%s\" 을(를) 정말 삭제할까요?", "MOD_ShadowFieldExciter", "Preset_Delete_Content")
		Set("프리셋 삭제", "MOD_ShadowFieldExciter", "Preset_Delete_Title")
		Set("프리셋 설명 :", "MOD_ShadowFieldExciter", "Preset_Desc")
		Set("프리셋 이름 :", "MOD_ShadowFieldExciter", "Preset_Name")
		Set("프리셋", "MOD_ShadowFieldExciter", "Preset_Title")
		Set("그림자장 여기기", "NAMES", "SHADOWFIELDEXCITER")
		Set("자동화 만세!", "RECIPE_DESC", "SHADOWFIELDEXCITER")
	end end)

	-- Large Chest (HD)  (workshop-2087177552)  9개
	pcall(function() if Apply("2087177552") then
		Set("아주 근사한걸!", "CHARACTERS", "GENERIC", "DESCRIBE", "LARGECHEST")
		Set("냉기의 힘을 손에 넣었다!", "CHARACTERS", "GENERIC", "DESCRIBE", "LARGEICEBOX")
		Set("무게만큼의 금보다 값지군!", "CHARACTERS", "GENERIC", "DESCRIBE", "LARGESALTBOX")
		Set("대형 상자", "NAMES", "LARGECHEST")
		Set("대형 아이스박스", "NAMES", "LARGEICEBOX")
		Set("대형 소금상자", "NAMES", "LARGESALTBOX")
		Set("더 많이 넣을 수 있는 큰 상자.", "RECIPE_DESC", "LARGECHEST")
		Set("거대한 아이스박스.", "RECIPE_DESC", "LARGEICEBOX")
		Set("전보다 더 짭짤하다.", "RECIPE_DESC", "LARGESALTBOX")
	end end)

	-- ActionQueue RB3  (workshop-2873533916)  9개
	pcall(function() if Apply("2873533916") then
		Set("자동 줍기 : ", "AQ_AUTOCOLLECT")
		Set("벌목 모드", "AQ_AUTOCOLLECT_CHOP")
		Set("일반 모드", "AQ_AUTOCOLLECT_NORMAL")
		Set("마지막 제작법 다시 만들기 : ", "AQ_CRAFTLAST")
		Set("무한 설치 : ", "AQ_ENDLESSDEPLOY")
		Set("꺼짐", "AQ_FALSE")
		Set("마지막에 만든 제작법을 찾을 수 없습니다", "AQ_NORECIPEFOUND")
		Set("켜짐", "AQ_TRUE")
		Set("제작할 수 없음 : ", "AQ_UNABLECRAFT")
	end end)

	-- Winona's Porta-base V2  (workshop-3569101848)  5개
	pcall(function() if Apply("3569101848") then
		Set("하! 이제 짐 들고 다닐 일 없겠네.", "CHARACTERS", "WINONA", "DESCRIBE", "WINONA_MOVING_BOX")
		Set("정어리 통조림보다 빽빽하게 넣었어!", "CHARACTERS", "WINONA", "DESCRIBE", "WINONA_MOVING_BOX_ITEM")
		Set("위노나의 이동식 기지", "NAMES", "WINONA_MOVING_BOX")
		Set("위노나의 이동식 기지", "NAMES", "WINONA_MOVING_BOX_ITEM")
		Set("발명품을 통째로 싸서 옮기는 설치형 발판.", "RECIPE_DESC", "WINONA_MOVING_BOX_ITEM")
	end end)
end

-- 한 번만 덮어쓰면 늦게 올라온 모드가 다시 제 글자로 되돌려 놓을 수 있습니다.
-- 그래서 월드가 다 뜬 뒤 한 번 더 부릅니다. 같은 값을 다시 넣는 것이라
-- 두 번 해도 문제가 없습니다.
local ok, err = pcall(Translate)
if not ok then
	print("[한글패치] 적용하지 못했습니다: " .. tostring(err))
	return
end

AddSimPostInit(function()
	pcall(Translate)
end)
